const MOVIES_BOLLYWOOD = [
  { title: "Dilwale Dulhania Le Jayenge", difficulty: "easy", popularity: "popular" },
  { title: "Sholay", difficulty: "easy", popularity: "popular" },
  { title: "Kuch Kuch Hota Hai", difficulty: "easy", popularity: "popular" },
  { title: "3 Idiots", difficulty: "easy", popularity: "popular" },
  { title: "Dangal", difficulty: "easy", popularity: "popular" },
  { title: "PK", difficulty: "easy", popularity: "popular" },
  { title: "Kabhi Khushi Kabhie Gham", difficulty: "easy", popularity: "popular" },
  { title: "Dhoom", difficulty: "easy", popularity: "popular" },
  { title: "Bajrangi Bhaijaan", difficulty: "easy", popularity: "popular" },
  { title: "Pathaan", difficulty: "easy", popularity: "popular" },
  { title: "Stree", difficulty: "easy", popularity: "popular" },
  { title: "Jawan", difficulty: "easy", popularity: "popular" },
  { title: "Animal", difficulty: "easy", popularity: "popular" },
  { title: "Zindagi Na Milegi Dobara", difficulty: "easy", popularity: "popular" },
  { title: "Hera Pheri", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Andaz Apna Apna", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Munnabhai MBBS", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Mr India", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Pakeezah", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Boot Polish", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Lagaan", difficulty: "medium", popularity: "popular" },
  { title: "Taare Zameen Par", difficulty: "medium", popularity: "popular" },
  { title: "Queen", difficulty: "medium", popularity: "popular" },
  { title: "Gangs of Wasseypur", difficulty: "medium", popularity: "popular" },
  { title: "Andhadhun", difficulty: "medium", popularity: "popular" },
  { title: "The Kashmir Files", difficulty: "medium", popularity: "popular" },
  { title: "12th Fail", difficulty: "medium", popularity: "popular" },
  { title: "Shershaah", difficulty: "medium", popularity: "popular" },
  { title: "Kahaani", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Tumbbad", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Udaan", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Ship of Theseus", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Pyaasa", difficulty: "hard", popularity: "popular" },
  { title: "Mughal-E-Azam", difficulty: "hard", popularity: "popular" },
  { title: "Jaane Bhi Do Yaaro", difficulty: "hard", popularity: "not-so-popular" },
];
