const MOVIES_BOLLYWOOD = [
  // ── EASY + POPULAR ────────────────────────────────────────────────────────
  { title: "Dilwale Dulhania Le Jayenge", difficulty: "easy", popularity: "popular" },
  { title: "Sholay", difficulty: "easy", popularity: "popular" },
  { title: "Kuch Kuch Hota Hai", difficulty: "easy", popularity: "popular" },
  { title: "3 Idiots", difficulty: "easy", popularity: "popular" },
  { title: "Dangal", difficulty: "easy", popularity: "popular" },
  { title: "Baahubali", difficulty: "easy", popularity: "popular" },
  { title: "PK", difficulty: "easy", popularity: "popular" },
  { title: "Chennai Express", difficulty: "easy", popularity: "popular" },
  { title: "Kabhi Khushi Kabhie Gham", difficulty: "easy", popularity: "popular" },
  { title: "Hum Aapke Hain Koun", difficulty: "easy", popularity: "popular" },
  { title: "Dilwale", difficulty: "easy", popularity: "popular" },
  { title: "Padmaavat", difficulty: "easy", popularity: "popular" },
  { title: "Tiger Zinda Hai", difficulty: "easy", popularity: "popular" },
  { title: "Dhoom", difficulty: "easy", popularity: "popular" },
  { title: "Don", difficulty: "easy", popularity: "popular" },
  { title: "Dhoom 2", difficulty: "easy", popularity: "popular" },
  { title: "Don 2", difficulty: "easy", popularity: "popular" },
  { title: "War", difficulty: "easy", popularity: "popular" },
  { title: "Pathaan", difficulty: "easy", popularity: "popular" },
  { title: "Jawan", difficulty: "easy", popularity: "popular" },
  { title: "Animal", difficulty: "easy", popularity: "popular" },
  { title: "Gadar 2", difficulty: "easy", popularity: "popular" },
  { title: "OMG 2", difficulty: "easy", popularity: "popular" },
  { title: "Rocky Aur Rani Ki Prem Kahani", difficulty: "easy", popularity: "popular" },
  { title: "Brahmastra", difficulty: "easy", popularity: "popular" },
  { title: "Bharat", difficulty: "easy", popularity: "popular" },
  { title: "Race 3", difficulty: "easy", popularity: "popular" },
  { title: "Thugs of Hindostan", difficulty: "easy", popularity: "popular" },
  { title: "Simmba", difficulty: "easy", popularity: "popular" },
  { title: "Sooryavanshi", difficulty: "easy", popularity: "popular" },
  { title: "KGF Chapter 1", difficulty: "easy", popularity: "popular" },
  { title: "KGF Chapter 2", difficulty: "easy", popularity: "popular" },
  { title: "RRR", difficulty: "easy", popularity: "popular" },
  { title: "Pushpa The Rise", difficulty: "easy", popularity: "popular" },
  { title: "Student of the Year", difficulty: "easy", popularity: "popular" },
  { title: "Yeh Jawaani Hai Deewani", difficulty: "easy", popularity: "popular" },
  { title: "Aashiqui 2", difficulty: "easy", popularity: "popular" },
  { title: "Queen", difficulty: "easy", popularity: "popular" },
  { title: "Raazi", difficulty: "easy", popularity: "popular" },
  { title: "Uri The Surgical Strike", difficulty: "easy", popularity: "popular" },
  { title: "Kesari", difficulty: "easy", popularity: "popular" },
  { title: "Super 30", difficulty: "easy", popularity: "popular" },
  { title: "Bala", difficulty: "easy", popularity: "popular" },
  { title: "Good Newwz", difficulty: "easy", popularity: "popular" },
  { title: "Stree", difficulty: "easy", popularity: "popular" },
  { title: "Bhediya", difficulty: "easy", popularity: "popular" },
  { title: "Dil Dhadakne Do", difficulty: "easy", popularity: "popular" },
  { title: "Bajrangi Bhaijaan", difficulty: "easy", popularity: "popular" },
  { title: "Sultan", difficulty: "easy", popularity: "popular" },
  { title: "Tubelight", difficulty: "easy", popularity: "popular" },
  { title: "Race", difficulty: "easy", popularity: "popular" },
  { title: "Race 2", difficulty: "easy", popularity: "popular" },
  { title: "Mughal-E-Azam", difficulty: "easy", popularity: "popular" },
  { title: "Hum", difficulty: "easy", popularity: "popular" },
  { title: "Jo Jeeta Wohi Sikandar", difficulty: "easy", popularity: "popular" },
  { title: "Dil Se", difficulty: "easy", popularity: "popular" },
  { title: "Zindagi Na Milegi Dobara", difficulty: "easy", popularity: "popular" },
  { title: "Band Baaja Baaraat", difficulty: "easy", popularity: "popular" },
  { title: "Barfi", difficulty: "easy", popularity: "popular" },
  { title: "Highway", difficulty: "easy", popularity: "popular" },
  { title: "Bareilly Ki Barfi", difficulty: "easy", popularity: "popular" },
  { title: "Shubh Mangal Saavdhan", difficulty: "easy", popularity: "popular" },
  { title: "Roohi", difficulty: "easy", popularity: "popular" },
  { title: "Dil", difficulty: "easy", popularity: "popular" },

  // ── EASY + NOT-SO-POPULAR ─────────────────────────────────────────────────
  { title: "Gadar Ek Prem Katha", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Tere Naam", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Wanted", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Dabangg", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Dabangg 2", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Dabangg 3", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Rowdy Rathore", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Son of Sardaar", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Bol Bachchan", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Housefull", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Housefull 2", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Grand Masti", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Golmaal", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Golmaal Again", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Singham", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Singham Returns", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Ek Tha Tiger", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Bang Bang", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Kick", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Heropanti", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Lootera", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Raanjhanaa", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Kai Po Che", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Fukrey", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Hera Pheri", difficulty: "easy", popularity: "not-so-popular" },

  // ── EASY + RARELY-HEARD ───────────────────────────────────────────────────
  { title: "Bombai Ka Babu", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Tumse Na Ho Payega", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Love in Simla", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Waqt", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Pyar Kiya To Darna Kya", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Jab Pyar Kisise Hota Hai", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Mere Mehboob", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Professor", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Dil Tera Deewana", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Teen Devian", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Ek Phool Do Mali", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Shikar", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Khilona", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Anand", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Haathi Mere Saathi", difficulty: "easy", popularity: "rarely-heard" },

  // ── MEDIUM + POPULAR ──────────────────────────────────────────────────────
  { title: "Dil Chahta Hai", difficulty: "medium", popularity: "popular" },
  { title: "Lagaan", difficulty: "medium", popularity: "popular" },
  { title: "Taare Zameen Par", difficulty: "medium", popularity: "popular" },
  { title: "Rockstar", difficulty: "medium", popularity: "popular" },
  { title: "Gangs of Wasseypur", difficulty: "medium", popularity: "popular" },
  { title: "Gangs of Wasseypur 2", difficulty: "medium", popularity: "popular" },
  { title: "Kahaani", difficulty: "medium", popularity: "popular" },
  { title: "Andhadhun", difficulty: "medium", popularity: "popular" },
  { title: "Article 15", difficulty: "medium", popularity: "popular" },
  { title: "Thappad", difficulty: "medium", popularity: "popular" },
  { title: "Gulabo Sitabo", difficulty: "medium", popularity: "popular" },
  { title: "Shakuntala Devi", difficulty: "medium", popularity: "popular" },
  { title: "Sardar Udham", difficulty: "medium", popularity: "popular" },
  { title: "Shershaah", difficulty: "medium", popularity: "popular" },
  { title: "Bell Bottom", difficulty: "medium", popularity: "popular" },
  { title: "Bhool Bhulaiyaa 2", difficulty: "medium", popularity: "popular" },
  { title: "Badhaai Ho", difficulty: "medium", popularity: "popular" },
  { title: "Badhaai Do", difficulty: "medium", popularity: "popular" },
  { title: "Shubh Mangal Zyada Saavdhan", difficulty: "medium", popularity: "popular" },
  { title: "Luka Chuppi", difficulty: "medium", popularity: "popular" },
  { title: "De De Pyaar De", difficulty: "medium", popularity: "popular" },
  { title: "Total Dhamaal", difficulty: "medium", popularity: "popular" },
  { title: "Manikarnika", difficulty: "medium", popularity: "popular" },
  { title: "Panga", difficulty: "medium", popularity: "popular" },
  { title: "Dil Bechara", difficulty: "medium", popularity: "popular" },
  { title: "Lal Singh Chaddha", difficulty: "medium", popularity: "popular" },
  { title: "Shamshera", difficulty: "medium", popularity: "popular" },
  { title: "Border", difficulty: "medium", popularity: "popular" },
  { title: "Refugee", difficulty: "medium", popularity: "popular" },
  { title: "Taal", difficulty: "medium", popularity: "popular" },
  { title: "Devdas", difficulty: "medium", popularity: "popular" },
  { title: "Om Shanti Om", difficulty: "medium", popularity: "popular" },
  { title: "Rab Ne Bana Di Jodi", difficulty: "medium", popularity: "popular" },
  { title: "Cocktail", difficulty: "medium", popularity: "popular" },
  { title: "Student of the Year 2", difficulty: "medium", popularity: "popular" },
  { title: "Kalank", difficulty: "medium", popularity: "popular" },
  { title: "Saand Ki Aankh", difficulty: "medium", popularity: "popular" },
  { title: "Delhi Crime", difficulty: "medium", popularity: "popular" },
  { title: "Mirzapur", difficulty: "medium", popularity: "popular" },
  { title: "The Kashmir Files", difficulty: "medium", popularity: "popular" },
  { title: "12th Fail", difficulty: "medium", popularity: "popular" },
  { title: "Sam Bahadur", difficulty: "medium", popularity: "popular" },
  { title: "Fighter", difficulty: "medium", popularity: "popular" },
  { title: "Dunki", difficulty: "medium", popularity: "popular" },
  { title: "Tiger 3", difficulty: "medium", popularity: "popular" },
  { title: "Piku", difficulty: "medium", popularity: "popular" },
  { title: "Drishyam", difficulty: "medium", popularity: "popular" },
  { title: "Drishyam 2", difficulty: "medium", popularity: "popular" },
  { title: "Raid", difficulty: "medium", popularity: "popular" },
  { title: "Satyameva Jayate", difficulty: "medium", popularity: "popular" },
  { title: "Batla House", difficulty: "medium", popularity: "popular" },
  { title: "Section 375", difficulty: "medium", popularity: "popular" },
  { title: "Chhichhore", difficulty: "medium", popularity: "popular" },
  { title: "Pati Patni Aur Woh", difficulty: "medium", popularity: "popular" },
  { title: "Judgementall Hai Kya", difficulty: "medium", popularity: "popular" },
  { title: "Dream Girl", difficulty: "medium", popularity: "popular" },
  { title: "Ishqiya", difficulty: "medium", popularity: "popular" },
  { title: "Haider", difficulty: "medium", popularity: "popular" },
  { title: "Talvar", difficulty: "medium", popularity: "popular" },
  { title: "Aashiqui", difficulty: "medium", popularity: "popular" },
  { title: "Saawariya", difficulty: "medium", popularity: "popular" },
  { title: "Hero", difficulty: "medium", popularity: "popular" },

  // ── MEDIUM + NOT-SO-POPULAR ───────────────────────────────────────────────
  { title: "Dedh Ishqiya", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Aligarh", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Margarita with a Straw", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Court", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Masaan", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Titli", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Liar's Dice", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Qissa", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Ugly", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Bombay Talkies", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Bombay Velvet", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Bard of Blood", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Arjun Patiala", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Khandaani Shafakhana", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Jabariya Jodi", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Malaal", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Mukkabaaz", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Newton", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Photograph", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Village Rockstars", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Bulbbul", difficulty: "medium", popularity: "not-so-popular" },
  { title: "AK vs AK", difficulty: "medium", popularity: "not-so-popular" },
  { title: "A Thursday", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Mimi", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Sardar Ka Grandson", difficulty: "medium", popularity: "not-so-popular" },

  // ── MEDIUM + RARELY-HEARD ─────────────────────────────────────────────────
  { title: "Udaan", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Ship of Theseus", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Ankhon Dekhi", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Kothanodi", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Peepli Live", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Fandry", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Sairat", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Chauthi Koot", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Nanak Shah Fakir", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Raman Raghav 2.0", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Trapped", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Omerta", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Manto", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Tumhari Sulu", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Aamis", difficulty: "medium", popularity: "rarely-heard" },

  // ── HARD + POPULAR ────────────────────────────────────────────────────────
  { title: "Pyaasa", difficulty: "hard", popularity: "popular" },
  { title: "Kagaz Ke Phool", difficulty: "hard", popularity: "popular" },
  { title: "Guide", difficulty: "hard", popularity: "popular" },
  { title: "Teesri Manzil", difficulty: "hard", popularity: "popular" },
  { title: "Aradhana", difficulty: "hard", popularity: "popular" },
  { title: "Do Bigha Zamin", difficulty: "hard", popularity: "popular" },
  { title: "Awaara", difficulty: "hard", popularity: "popular" },
  { title: "Shree 420", difficulty: "hard", popularity: "popular" },
  { title: "Boot Polish", difficulty: "hard", popularity: "popular" },
  { title: "Jagte Raho", difficulty: "hard", popularity: "popular" },
  { title: "Mother India", difficulty: "hard", popularity: "popular" },
  { title: "Ab Dilli Dur Nahin", difficulty: "hard", popularity: "popular" },
  { title: "Baazi", difficulty: "hard", popularity: "popular" },
  { title: "Nagin", difficulty: "hard", popularity: "popular" },
  { title: "CID", difficulty: "hard", popularity: "popular" },
  { title: "Taxi Driver Bollywood", difficulty: "hard", popularity: "popular" },
  { title: "Funtoosh", difficulty: "hard", popularity: "popular" },
  { title: "Barsaat", difficulty: "hard", popularity: "popular" },
  { title: "Andaaz", difficulty: "hard", popularity: "popular" },
  { title: "Devdas Classic", difficulty: "hard", popularity: "popular" },

  // ── HARD + NOT-SO-POPULAR ─────────────────────────────────────────────────
  { title: "Ardh Satya", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Jaane Bhi Do Yaaro", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Chakra", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Ankush", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Arth", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Mandi", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Sparsh", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Kalyug", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Junoon", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Sadgati", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Manthan", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Bhumika", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Nishant", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Ankur", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Kondura", difficulty: "hard", popularity: "not-so-popular" },

  // ── HARD + RARELY-HEARD ───────────────────────────────────────────────────
  { title: "Subarnarekha", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Meghe Dhaka Tara", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Jalsaghar", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Charulata", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Aparajito", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Pather Panchali", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Elippathayam", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Piravi", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Kodiyettam", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Swayamvaram", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Kanchana Sita", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Nizhalkuthu", difficulty: "hard", popularity: "rarely-heard" },

  // ── EASY + POPULAR (additional) ──────────────────────────────────────────
  { title: "Kabir Singh", difficulty: "easy", popularity: "popular" },
  { title: "Bhool Bhulaiyaa", difficulty: "easy", popularity: "popular" },
  { title: "Koi Mil Gaya", difficulty: "easy", popularity: "popular" },
  { title: "Fanaa", difficulty: "easy", popularity: "popular" },
  { title: "Salaam Namaste", difficulty: "easy", popularity: "popular" },
  { title: "Kal Ho Na Ho", difficulty: "easy", popularity: "popular" },
  { title: "Veer-Zaara", difficulty: "easy", popularity: "popular" },
  { title: "Mohabbatein", difficulty: "easy", popularity: "popular" },
  { title: "Kabhi Alvida Naa Kehna", difficulty: "easy", popularity: "popular" },
  { title: "Main Hoon Na", difficulty: "easy", popularity: "popular" },
  { title: "Bunty Aur Babli", difficulty: "easy", popularity: "popular" },
  { title: "Dhoom 3", difficulty: "easy", popularity: "popular" },
  { title: "Happy New Year", difficulty: "easy", popularity: "popular" },
  { title: "Muqaddar Ka Sikandar", difficulty: "easy", popularity: "popular" },
  { title: "Amar Akbar Anthony", difficulty: "easy", popularity: "popular" },
  { title: "Deewar", difficulty: "easy", popularity: "popular" },
  { title: "Mr. India", difficulty: "easy", popularity: "popular" },
  { title: "Ram Lakhan", difficulty: "easy", popularity: "popular" },
  { title: "Rangeela", difficulty: "easy", popularity: "popular" },
  { title: "Dil To Pagal Hai", difficulty: "easy", popularity: "popular" },
  { title: "Kaho Naa Pyaar Hai", difficulty: "easy", popularity: "popular" },
  { title: "Krrish", difficulty: "easy", popularity: "popular" },
  { title: "Krrish 3", difficulty: "easy", popularity: "popular" },
  { title: "Baazigar", difficulty: "easy", popularity: "popular" },
  { title: "Darr", difficulty: "easy", popularity: "popular" },
  { title: "Agneepath", difficulty: "easy", popularity: "popular" },
  { title: "Ghulam", difficulty: "easy", popularity: "popular" },
  { title: "Hum Tum", difficulty: "easy", popularity: "popular" },
  { title: "Baaghi", difficulty: "easy", popularity: "popular" },
  { title: "Baaghi 2", difficulty: "easy", popularity: "popular" },
  { title: "Baaghi 3", difficulty: "easy", popularity: "popular" },
  { title: "Tanhaji", difficulty: "easy", popularity: "popular" },
  { title: "83", difficulty: "easy", popularity: "popular" },
  { title: "Ae Dil Hai Mushkil", difficulty: "easy", popularity: "popular" },
  { title: "Raees", difficulty: "easy", popularity: "popular" },
  { title: "Kaabil", difficulty: "easy", popularity: "popular" },
  { title: "Bajirao Mastani", difficulty: "easy", popularity: "popular" },
  { title: "Ram-Leela", difficulty: "easy", popularity: "popular" },
  { title: "Padman", difficulty: "easy", popularity: "popular" },
  { title: "Toilet Ek Prem Katha", difficulty: "easy", popularity: "popular" },
  { title: "Prem Ratan Dhan Payo", difficulty: "easy", popularity: "popular" },
  { title: "Welcome", difficulty: "easy", popularity: "popular" },
  { title: "Welcome Back", difficulty: "easy", popularity: "popular" },
  { title: "Ready", difficulty: "easy", popularity: "popular" },
  { title: "Bodyguard", difficulty: "easy", popularity: "popular" },
  { title: "Judwaa 2", difficulty: "easy", popularity: "popular" },
  { title: "Jab Tak Hai Jaan", difficulty: "easy", popularity: "popular" },
  { title: "Tamasha", difficulty: "easy", popularity: "popular" },
  { title: "Jab Harry Met Sejal", difficulty: "easy", popularity: "popular" },
  { title: "Zero", difficulty: "easy", popularity: "popular" },
  { title: "Atrangi Re", difficulty: "easy", popularity: "popular" },
  { title: "Chandigarh Kare Aashiqui", difficulty: "easy", popularity: "popular" },
  { title: "Haseen Dillruba", difficulty: "easy", popularity: "popular" },
  { title: "Gehraiyaan", difficulty: "easy", popularity: "popular" },
  { title: "Liger", difficulty: "easy", popularity: "popular" },
  { title: "Vikram Vedha Hindi", difficulty: "easy", popularity: "popular" },
  { title: "Heropanti 2", difficulty: "easy", popularity: "popular" },
  { title: "Radhe", difficulty: "easy", popularity: "popular" },
  { title: "Andaz Apna Apna", difficulty: "easy", popularity: "popular" },
  { title: "Judwaa", difficulty: "easy", popularity: "popular" },
  { title: "Sarfarosh", difficulty: "easy", popularity: "popular" },
  { title: "Sadak", difficulty: "easy", popularity: "popular" },
  { title: "Deewana", difficulty: "easy", popularity: "popular" },
  { title: "Pardes", difficulty: "easy", popularity: "popular" },
  { title: "Chandni", difficulty: "easy", popularity: "popular" },
  { title: "Tezaab", difficulty: "easy", popularity: "popular" },
  { title: "Khalnayak", difficulty: "easy", popularity: "popular" },
  { title: "Josh", difficulty: "easy", popularity: "popular" },
  { title: "Mujhse Dosti Karoge", difficulty: "easy", popularity: "popular" },
  { title: "Fitoor", difficulty: "easy", popularity: "popular" },
  { title: "Once Upon a Time in Mumbaai", difficulty: "easy", popularity: "popular" },
  { title: "Asoka", difficulty: "easy", popularity: "popular" },
  { title: "Hum Saath Saath Hain", difficulty: "easy", popularity: "popular" },
  { title: "Chalte Chalte", difficulty: "easy", popularity: "popular" },
  { title: "Partner", difficulty: "easy", popularity: "popular" },
  { title: "Golmaal Returns", difficulty: "easy", popularity: "popular" },
  { title: "Sanju", difficulty: "easy", popularity: "popular" },
  { title: "Stree 2", difficulty: "easy", popularity: "popular" },
  { title: "Singham Again", difficulty: "easy", popularity: "popular" },
  { title: "Bhool Bhulaiyaa 3", difficulty: "easy", popularity: "popular" },
  { title: "Laapataa Ladies", difficulty: "easy", popularity: "popular" },
  { title: "Article 370", difficulty: "easy", popularity: "popular" },
  { title: "Maidaan", difficulty: "easy", popularity: "popular" },
  { title: "Fighter", difficulty: "easy", popularity: "popular" },
  { title: "Devara Hindi", difficulty: "easy", popularity: "popular" },
  { title: "Kalki 2898 AD", difficulty: "easy", popularity: "popular" },

  // ── EASY + NOT-SO-POPULAR (additional) ───────────────────────────────────
  { title: "Golmaal 3", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Golmaal Fun Unlimited", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Housefull 3", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Housefull 4", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Coolie No 1", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Hero No 1", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Biwi No 1", difficulty: "easy", popularity: "not-so-popular" },
  { title: "No Entry", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Phir Hera Pheri", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Mujhse Shaadi Karogi", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Bhagam Bhag", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Dhamaal", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Double Dhamaal", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Aankhen", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Baadshah", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Duplicate", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Koyla", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Ram Jaane", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Tees Maar Khan", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Fukrey Returns", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Fukrey 3", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Shaitaan", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Crew", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Bade Miyan Chote Miyan", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Thank God", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Cirkus", difficulty: "easy", popularity: "not-so-popular" },
  { title: "An Action Hero", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Veer", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Murder", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Murder 2", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Raaz", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Bhoot", difficulty: "easy", popularity: "not-so-popular" },
  { title: "1920", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Hate Story", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Kaante", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Shootout at Lokhandwala", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Shootout at Wadala", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Love Sex Aur Dhokha", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Pyaar Ka Punchnama", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Pyaar Ka Punchnama 2", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Sonu Ke Titu Ki Sweety", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Selfiee", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Kisi Ka Bhai Kisi Ki Jaan", difficulty: "easy", popularity: "not-so-popular" },

  // ── EASY + RARELY-HEARD (additional) ─────────────────────────────────────
  { title: "Pakeezah", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Hare Rama Hare Krishna", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Aap Ki Kasam", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Roti Kapda Aur Makaan", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Aandhi", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Mausam", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Purab Aur Paschim", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Suhaag", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Naseeb", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Satte Pe Satta", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Sharaabi", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Toofan", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Mere Jeevan Saathi", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Safar", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Kati Patang", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Do Raaste", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Baiju Bawra", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Aan", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Bahar", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Dard", difficulty: "easy", popularity: "rarely-heard" },

  // ── MEDIUM + POPULAR (additional) ────────────────────────────────────────
  { title: "Swades", difficulty: "medium", popularity: "popular" },
  { title: "Rang De Basanti", difficulty: "medium", popularity: "popular" },
  { title: "Black", difficulty: "medium", popularity: "popular" },
  { title: "Lage Raho Munna Bhai", difficulty: "medium", popularity: "popular" },
  { title: "Munna Bhai MBBS", difficulty: "medium", popularity: "popular" },
  { title: "Jab We Met", difficulty: "medium", popularity: "popular" },
  { title: "Love Aaj Kal", difficulty: "medium", popularity: "popular" },
  { title: "Wake Up Sid", difficulty: "medium", popularity: "popular" },
  { title: "Dum Laga Ke Haisha", difficulty: "medium", popularity: "popular" },
  { title: "Tanu Weds Manu", difficulty: "medium", popularity: "popular" },
  { title: "Tanu Weds Manu Returns", difficulty: "medium", popularity: "popular" },
  { title: "Special 26", difficulty: "medium", popularity: "popular" },
  { title: "Baby", difficulty: "medium", popularity: "popular" },
  { title: "Airlift", difficulty: "medium", popularity: "popular" },
  { title: "A Wednesday", difficulty: "medium", popularity: "popular" },
  { title: "Neerja", difficulty: "medium", popularity: "popular" },
  { title: "Pink", difficulty: "medium", popularity: "popular" },
  { title: "Rustom", difficulty: "medium", popularity: "popular" },
  { title: "M.S. Dhoni The Untold Story", difficulty: "medium", popularity: "popular" },
  { title: "Bhaag Milkha Bhaag", difficulty: "medium", popularity: "popular" },
  { title: "Mary Kom", difficulty: "medium", popularity: "popular" },
  { title: "Paan Singh Tomar", difficulty: "medium", popularity: "popular" },
  { title: "Citylights", difficulty: "medium", popularity: "popular" },
  { title: "Force", difficulty: "medium", popularity: "popular" },
  { title: "Madras Cafe", difficulty: "medium", popularity: "popular" },
  { title: "NH10", difficulty: "medium", popularity: "popular" },
  { title: "Mardaani", difficulty: "medium", popularity: "popular" },
  { title: "Mardaani 2", difficulty: "medium", popularity: "popular" },
  { title: "English Vinglish", difficulty: "medium", popularity: "popular" },
  { title: "Tere Bin Laden", difficulty: "medium", popularity: "popular" },
  { title: "Shanghai", difficulty: "medium", popularity: "popular" },
  { title: "Ghajini Hindi", difficulty: "medium", popularity: "popular" },
  { title: "The Lunchbox", difficulty: "medium", popularity: "popular" },
  { title: "Dhamaka", difficulty: "medium", popularity: "popular" },
  { title: "Adipurush", difficulty: "medium", popularity: "popular" },
  { title: "Kapoor and Sons", difficulty: "medium", popularity: "popular" },
  { title: "2 States", difficulty: "medium", popularity: "popular" },
  { title: "OMG Oh My God", difficulty: "medium", popularity: "popular" },
  { title: "Kahaani 2", difficulty: "medium", popularity: "popular" },
  { title: "Kaminey", difficulty: "medium", popularity: "popular" },
  { title: "Dev D", difficulty: "medium", popularity: "popular" },
  { title: "Luck by Chance", difficulty: "medium", popularity: "popular" },
  { title: "Do Patti", difficulty: "medium", popularity: "popular" },
  { title: "Jigra", difficulty: "medium", popularity: "popular" },
  { title: "Satyaprem Ki Katha", difficulty: "medium", popularity: "popular" },
  { title: "Zara Hatke Zara Bachke", difficulty: "medium", popularity: "popular" },
  { title: "Dream Girl 2", difficulty: "medium", popularity: "popular" },
  { title: "Sui Dhaaga", difficulty: "medium", popularity: "popular" },
  { title: "Laila Majnu", difficulty: "medium", popularity: "popular" },
  { title: "Dobaaraa", difficulty: "medium", popularity: "popular" },
  { title: "Freddy", difficulty: "medium", popularity: "popular" },
  { title: "Lootcase", difficulty: "medium", popularity: "popular" },
  { title: "Shiddat", difficulty: "medium", popularity: "popular" },
  { title: "Tadap", difficulty: "medium", popularity: "popular" },
  { title: "Darlings", difficulty: "medium", popularity: "popular" },
  { title: "OK Jaanu", difficulty: "medium", popularity: "popular" },
  { title: "Half Girlfriend", difficulty: "medium", popularity: "popular" },
  { title: "Finding Fanny", difficulty: "medium", popularity: "popular" },
  { title: "Ishaqzaade", difficulty: "medium", popularity: "popular" },
  { title: "Merry Christmas", difficulty: "medium", popularity: "popular" },
  { title: "Sector 36", difficulty: "medium", popularity: "popular" },
  { title: "Phir Aayi Hasseen Dillruba", difficulty: "medium", popularity: "popular" },
  { title: "Kho Gaye Hum Kahan", difficulty: "medium", popularity: "popular" },
  { title: "Rajma Chawal", difficulty: "medium", popularity: "popular" },
  { title: "Joram", difficulty: "medium", popularity: "popular" },
  { title: "Do Aur Do Pyaar", difficulty: "medium", popularity: "popular" },
  { title: "Kill", difficulty: "medium", popularity: "popular" },
  { title: "Auron Mein Kahan Dum Tha", difficulty: "medium", popularity: "popular" },
  { title: "Vedaa", difficulty: "medium", popularity: "popular" },
  { title: "Stree 2 sequel" , difficulty: "medium", popularity: "popular" },
  { title: "Bawaal", difficulty: "medium", popularity: "popular" },
  { title: "Kuch Bheegi Aankhein", difficulty: "medium", popularity: "popular" },
  { title: "Merry Christmas 2024", difficulty: "medium", popularity: "popular" },
  { title: "Phule", difficulty: "medium", popularity: "popular" },
  { title: "Sky Force", difficulty: "medium", popularity: "popular" },
  { title: "Emergency", difficulty: "medium", popularity: "popular" },
  { title: "Chhaava", difficulty: "medium", popularity: "popular" },
  { title: "Loveyapa", difficulty: "medium", popularity: "popular" },
  { title: "Mere Husband Ki Biwi", difficulty: "medium", popularity: "popular" },
  { title: "Mufasa Hindi", difficulty: "medium", popularity: "popular" },
  { title: "Pushpa 2 The Rule", difficulty: "medium", popularity: "popular" },
  { title: "Singham 3", difficulty: "medium", popularity: "popular" },
  { title: "Welcome 3", difficulty: "medium", popularity: "popular" },
  { title: "Housefull 5", difficulty: "medium", popularity: "popular" },

  // ── MEDIUM + NOT-SO-POPULAR (additional) ─────────────────────────────────
  { title: "Vicky Donor", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Delhi Belly", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Oye Lucky Lucky Oye", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Shor in the City", difficulty: "medium", popularity: "not-so-popular" },
  { title: "LSD Love Sex Aur Dhokha", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Talaash", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Lootera", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Gangs of Wasseypur 3", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Baaghi 4", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Kahaani", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Kaasav", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Tumhari Pakhi", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Chauranga", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Barefoot to Goa", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Hawaazade", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Elizabeth Ekadashi", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Killa", difficulty: "medium", popularity: "not-so-popular" },
  { title: "I Am Kalam", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Gattu", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Stanley Ka Dabba", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Chillar Party", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Dhanak", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Kapkapi", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Mirzya", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Haraamkhor", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Tu Hai Mera Sunday", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Wazir", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Detective Byomkesh Bakshy", difficulty: "medium", popularity: "not-so-popular" },
  { title: "NH10", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Angry Indian Goddesses", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Ribbon", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Juice", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Pooja", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Bira The Vampire", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Kadambari", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Kaagaz", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Pagglait", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Mee Raqsam", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Durgamati", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Ginny Weds Sunny", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Ludo", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Dolly Kitty Aur Woh Chamakte Sitare", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Serious Men", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The White Tiger", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Milestone", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Mandela", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Uma", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Toofan", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Mumbai Diaries", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Jayeshbhai Jordaar", difficulty: "medium", popularity: "not-so-popular" },

  // ── MEDIUM + RARELY-HEARD (additional) ───────────────────────────────────
  { title: "Harud", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Gattu", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Miss Lovely", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Ba Baasha Ba", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Titli", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Saahas", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Iraivi", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Nanu Nanna Kanasu", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Chauthi Koot", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Visaranai", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Kumbakonam Gopinath", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Chithirayil Nilachandra", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Bonsai", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Nagraj Manjule", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Aankhon Dekhi", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Balak Palak", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Rege", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Natsamrat", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Sairat Marathi", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Cycle", difficulty: "medium", popularity: "rarely-heard" },

  // ── HARD + POPULAR (additional) ───────────────────────────────────────────
  { title: "Kismet", difficulty: "hard", popularity: "popular" },
  { title: "Aar Paar", difficulty: "hard", popularity: "popular" },
  { title: "Taxi Driver", difficulty: "hard", popularity: "popular" },
  { title: "House No 44", difficulty: "hard", popularity: "popular" },
  { title: "Paying Guest", difficulty: "hard", popularity: "popular" },
  { title: "Chalti Ka Naam Gaadi", difficulty: "hard", popularity: "popular" },
  { title: "Howrah Bridge", difficulty: "hard", popularity: "popular" },
  { title: "Mughal-E-Azam Classic", difficulty: "hard", popularity: "popular" },
  { title: "Madhumati", difficulty: "hard", popularity: "popular" },
  { title: "Gunga Jumna", difficulty: "hard", popularity: "popular" },
  { title: "Sangam", difficulty: "hard", popularity: "popular" },
  { title: "Himalay Ki God Mein", difficulty: "hard", popularity: "popular" },
  { title: "Brahmachari", difficulty: "hard", popularity: "popular" },
  { title: "Jewel Thief", difficulty: "hard", popularity: "popular" },
  { title: "Ittefaq", difficulty: "hard", popularity: "popular" },
  { title: "Aradhana Classic", difficulty: "hard", popularity: "popular" },
  { title: "Sachaa Jhutha", difficulty: "hard", popularity: "popular" },
  { title: "Amar Prem", difficulty: "hard", popularity: "popular" },
  { title: "Namak Haraam", difficulty: "hard", popularity: "popular" },
  { title: "Abhimaan", difficulty: "hard", popularity: "popular" },
  { title: "Dost", difficulty: "hard", popularity: "popular" },
  { title: "Majboor", difficulty: "hard", popularity: "popular" },
  { title: "Chupke Chupke", difficulty: "hard", popularity: "popular" },
  { title: "Mili", difficulty: "hard", popularity: "popular" },
  { title: "Sholay Prequel", difficulty: "hard", popularity: "popular" },
  { title: "Laawaris", difficulty: "hard", popularity: "popular" },
  { title: "Kranti", difficulty: "hard", popularity: "popular" },
  { title: "Naseeb Classic", difficulty: "hard", popularity: "popular" },
  { title: "Coolie", difficulty: "hard", popularity: "popular" },
  { title: "Trishul", difficulty: "hard", popularity: "popular" },
  { title: "Shakti", difficulty: "hard", popularity: "popular" },
  { title: "Silsila", difficulty: "hard", popularity: "popular" },
  { title: "Namak Halaal", difficulty: "hard", popularity: "popular" },
  { title: "Satte Pe Satta Classic", difficulty: "hard", popularity: "popular" },
  { title: "Mashaal", difficulty: "hard", popularity: "popular" },
  { title: "Sharaabi Classic", difficulty: "hard", popularity: "popular" },
  { title: "Inquilaab", difficulty: "hard", popularity: "popular" },
  { title: "Mard", difficulty: "hard", popularity: "popular" },
  { title: "Thokar", difficulty: "hard", popularity: "popular" },
  { title: "Toofan Classic", difficulty: "hard", popularity: "popular" },
  { title: "Hum", difficulty: "hard", popularity: "popular" },
  { title: "Baaghi Classic", difficulty: "hard", popularity: "popular" },
  { title: "Gopi", difficulty: "hard", popularity: "popular" },
  { title: "Johny Mera Naam", difficulty: "hard", popularity: "popular" },
  { title: "Sachaa Jhutha", difficulty: "hard", popularity: "popular" },
  { title: "Roti", difficulty: "hard", popularity: "popular" },
  { title: "Desh Premee Classic", difficulty: "hard", popularity: "popular" },
  { title: "Vidhaata", difficulty: "hard", popularity: "popular" },
  { title: "Mahaan", difficulty: "hard", popularity: "popular" },
  { title: "Andha Kanoon", difficulty: "hard", popularity: "popular" },

  // ── HARD + NOT-SO-POPULAR (additional) ────────────────────────────────────
  { title: "Suvarna Rekha", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Garm Hava", difficulty: "hard", popularity: "not-so-popular" },
  { title: "27 Down", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Gharaonda", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Chitchor", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Swami", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Doosra Aadmi", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Shaque", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Gehraai", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Grihapravesh", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Sitapur ki Geeta", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Shatranj Ke Khilari", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Junoon Classic", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Meera", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Kondura Classic", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Trikaal", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Pestonjee", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Dharavi", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Disha", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Rudaali", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Mammo", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Sardari Begum", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Naseem", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Is Raat Ki Subah Nahin", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Hazaar Chaurasi Ki Maa", difficulty: "hard", popularity: "not-so-popular" },

  // ── HARD + RARELY-HEARD (additional) ──────────────────────────────────────
  { title: "Bhuvan Shome", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Uski Roti", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Sara Akash", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Duvidha", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Nishant Classic", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Manthan Classic", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Bhumika Classic", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Junoon Parallel", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Kalyug Parallel", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Tarang", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Mohan Joshi Hazir Ho", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Aghaat", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Mirch Masala", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Tamas", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Salim Langde Pe Mat Ro", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Paar", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Khandhar", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Waaris", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Holi", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Massey Sahib", difficulty: "hard", popularity: "rarely-heard" },

  // ── EASY + POPULAR (final additions) ─────────────────────────────────────
  { title: "Ek Villain", difficulty: "easy", popularity: "popular" },
  { title: "Ek Villain Returns", difficulty: "easy", popularity: "popular" },
  { title: "Dil Juunglee", difficulty: "easy", popularity: "popular" },
  { title: "Dhadak", difficulty: "easy", popularity: "popular" },
  { title: "Notebook", difficulty: "easy", popularity: "popular" },
  { title: "Kesariya", difficulty: "easy", popularity: "popular" },
  { title: "Tu Jhoothi Main Makkaar", difficulty: "easy", popularity: "popular" },
  { title: "Satyameva Jayate 2", difficulty: "easy", popularity: "popular" },
  { title: "Baaghi 4", difficulty: "easy", popularity: "popular" },
  { title: "Mere Desh Ki Dharti", difficulty: "easy", popularity: "popular" },
  { title: "Kartik Calling Kartik", difficulty: "easy", popularity: "popular" },
  { title: "Pyaar Impossible", difficulty: "easy", popularity: "popular" },
  { title: "Tum Milo Toh Sahi", difficulty: "easy", popularity: "popular" },
  { title: "Cocktail 2", difficulty: "easy", popularity: "popular" },
  { title: "Aaja Nachle", difficulty: "easy", popularity: "popular" },
  { title: "Jaal The Trap", difficulty: "easy", popularity: "popular" },
  { title: "Vivah", difficulty: "easy", popularity: "popular" },
  { title: "Apne", difficulty: "easy", popularity: "popular" },
  { title: "Apne 2", difficulty: "easy", popularity: "popular" },
  { title: "Yamla Pagla Deewana", difficulty: "easy", popularity: "popular" },
  { title: "Son of Sardaar 2", difficulty: "easy", popularity: "popular" },
  { title: "Fukrey Boyzzz", difficulty: "easy", popularity: "popular" },
];
