const MOVIES_HOLLYWOOD = [
  { title: "Avatar", difficulty: "easy", popularity: "popular" },
  { title: "Titanic", difficulty: "easy", popularity: "popular" },
  { title: "The Lion King", difficulty: "easy", popularity: "popular" },
  { title: "Frozen", difficulty: "easy", popularity: "popular" },
  { title: "Toy Story", difficulty: "easy", popularity: "popular" },
  { title: "Spider-Man", difficulty: "easy", popularity: "popular" },
  { title: "Jurassic Park", difficulty: "easy", popularity: "popular" },
  { title: "Home Alone", difficulty: "easy", popularity: "popular" },
  { title: "Harry Potter", difficulty: "easy", popularity: "popular" },
  { title: "Star Wars", difficulty: "easy", popularity: "popular" },
  { title: "The Avengers", difficulty: "easy", popularity: "popular" },
  { title: "Finding Nemo", difficulty: "easy", popularity: "popular" },
  { title: "Shrek", difficulty: "easy", popularity: "popular" },
  { title: "Ice Age", difficulty: "easy", popularity: "popular" },
  { title: "The Mask", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Ace Ventura", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Mrs Doubtfire", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Space Jam", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Paulie", difficulty: "easy", popularity: "rarely-heard" },
  { title: "The Sandlot", difficulty: "easy", popularity: "rarely-heard" },
  { title: "The Dark Knight", difficulty: "medium", popularity: "popular" },
  { title: "Inception", difficulty: "medium", popularity: "popular" },
  { title: "Interstellar", difficulty: "medium", popularity: "popular" },
  { title: "The Matrix", difficulty: "medium", popularity: "popular" },
  { title: "Forrest Gump", difficulty: "medium", popularity: "popular" },
  { title: "The Godfather", difficulty: "medium", popularity: "popular" },
  { title: "Pulp Fiction", difficulty: "medium", popularity: "popular" },
  { title: "Fight Club", difficulty: "medium", popularity: "popular" },
  { title: "Good Will Hunting", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Memento", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Moon", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Coherence", difficulty: "medium", popularity: "rarely-heard" },
  { title: "2001 A Space Odyssey", difficulty: "hard", popularity: "popular" },
  { title: "Apocalypse Now", difficulty: "hard", popularity: "popular" },
  { title: "Mulholland Drive", difficulty: "hard", popularity: "not-so-popular" },
];
