const MOVIES_HOLLYWOOD = [
  // ── EASY + POPULAR ────────────────────────────────────────────────────────
  { title: "Avatar", difficulty: "easy", popularity: "popular" },
  { title: "Titanic", difficulty: "easy", popularity: "popular" },
  { title: "The Lion King", difficulty: "easy", popularity: "popular" },
  { title: "Frozen", difficulty: "easy", popularity: "popular" },
  { title: "Toy Story", difficulty: "easy", popularity: "popular" },
  { title: "Spider-Man", difficulty: "easy", popularity: "popular" },
  { title: "Batman", difficulty: "easy", popularity: "popular" },
  { title: "Jurassic Park", difficulty: "easy", popularity: "popular" },
  { title: "Home Alone", difficulty: "easy", popularity: "popular" },
  { title: "Harry Potter and the Sorcerer's Stone", difficulty: "easy", popularity: "popular" },
  { title: "Star Wars", difficulty: "easy", popularity: "popular" },
  { title: "The Avengers", difficulty: "easy", popularity: "popular" },
  { title: "Finding Nemo", difficulty: "easy", popularity: "popular" },
  { title: "Shrek", difficulty: "easy", popularity: "popular" },
  { title: "Pirates of the Caribbean", difficulty: "easy", popularity: "popular" },
  { title: "The Little Mermaid", difficulty: "easy", popularity: "popular" },
  { title: "Beauty and the Beast", difficulty: "easy", popularity: "popular" },
  { title: "Aladdin", difficulty: "easy", popularity: "popular" },
  { title: "The Incredibles", difficulty: "easy", popularity: "popular" },
  { title: "Up", difficulty: "easy", popularity: "popular" },
  { title: "WALL-E", difficulty: "easy", popularity: "popular" },
  { title: "Inside Out", difficulty: "easy", popularity: "popular" },
  { title: "Moana", difficulty: "easy", popularity: "popular" },
  { title: "Coco", difficulty: "easy", popularity: "popular" },
  { title: "Zootopia", difficulty: "easy", popularity: "popular" },
  { title: "Minions", difficulty: "easy", popularity: "popular" },
  { title: "Despicable Me", difficulty: "easy", popularity: "popular" },
  { title: "Madagascar", difficulty: "easy", popularity: "popular" },
  { title: "Ice Age", difficulty: "easy", popularity: "popular" },
  { title: "Cars", difficulty: "easy", popularity: "popular" },
  { title: "Ratatouille", difficulty: "easy", popularity: "popular" },
  { title: "Brave", difficulty: "easy", popularity: "popular" },
  { title: "Tangled", difficulty: "easy", popularity: "popular" },
  { title: "Big Hero 6", difficulty: "easy", popularity: "popular" },
  { title: "Wreck-It Ralph", difficulty: "easy", popularity: "popular" },
  { title: "Kung Fu Panda", difficulty: "easy", popularity: "popular" },
  { title: "How to Train Your Dragon", difficulty: "easy", popularity: "popular" },
  { title: "The Croods", difficulty: "easy", popularity: "popular" },
  { title: "Boss Baby", difficulty: "easy", popularity: "popular" },
  { title: "Trolls", difficulty: "easy", popularity: "popular" },
  { title: "The Secret Life of Pets", difficulty: "easy", popularity: "popular" },
  { title: "Sing", difficulty: "easy", popularity: "popular" },
  { title: "Captain America", difficulty: "easy", popularity: "popular" },
  { title: "Iron Man", difficulty: "easy", popularity: "popular" },
  { title: "Thor", difficulty: "easy", popularity: "popular" },
  { title: "Black Panther", difficulty: "easy", popularity: "popular" },
  { title: "Wonder Woman", difficulty: "easy", popularity: "popular" },
  { title: "Superman", difficulty: "easy", popularity: "popular" },
  { title: "Batman v Superman", difficulty: "easy", popularity: "popular" },
  { title: "Aquaman", difficulty: "easy", popularity: "popular" },
  { title: "Doctor Strange", difficulty: "easy", popularity: "popular" },
  { title: "Guardians of the Galaxy", difficulty: "easy", popularity: "popular" },
  { title: "Ant-Man", difficulty: "easy", popularity: "popular" },
  { title: "Deadpool", difficulty: "easy", popularity: "popular" },
  { title: "Logan", difficulty: "easy", popularity: "popular" },
  { title: "X-Men", difficulty: "easy", popularity: "popular" },
  { title: "Fast and Furious", difficulty: "easy", popularity: "popular" },
  { title: "Mission Impossible", difficulty: "easy", popularity: "popular" },
  { title: "Transformers", difficulty: "easy", popularity: "popular" },
  { title: "The Terminator", difficulty: "easy", popularity: "popular" },
  { title: "Rambo", difficulty: "easy", popularity: "popular" },
  { title: "Rocky", difficulty: "easy", popularity: "popular" },
  { title: "Top Gun", difficulty: "easy", popularity: "popular" },
  { title: "Jerry Maguire", difficulty: "easy", popularity: "popular" },
  { title: "Forrest Gump", difficulty: "easy", popularity: "popular" },
  { title: "Cast Away", difficulty: "easy", popularity: "popular" },
  { title: "The Mask", difficulty: "easy", popularity: "popular" },
  { title: "Ace Ventura", difficulty: "easy", popularity: "popular" },
  { title: "Dumb and Dumber", difficulty: "easy", popularity: "popular" },
  { title: "Home Alone 2", difficulty: "easy", popularity: "popular" },
  { title: "Toy Story 2", difficulty: "easy", popularity: "popular" },
  { title: "Toy Story 3", difficulty: "easy", popularity: "popular" },
  { title: "The Jungle Book", difficulty: "easy", popularity: "popular" },
  { title: "Encanto", difficulty: "easy", popularity: "popular" },
  { title: "Thor Ragnarok", difficulty: "easy", popularity: "popular" },
  { title: "Avengers Age of Ultron", difficulty: "easy", popularity: "popular" },
  { title: "Captain Marvel", difficulty: "easy", popularity: "popular" },
  { title: "Venom", difficulty: "easy", popularity: "popular" },
  { title: "Sonic the Hedgehog", difficulty: "easy", popularity: "popular" },
  { title: "Shazam", difficulty: "easy", popularity: "popular" },
  { title: "The Flash", difficulty: "easy", popularity: "popular" },
  { title: "Black Adam", difficulty: "easy", popularity: "popular" },
  { title: "Ant-Man and the Wasp", difficulty: "easy", popularity: "popular" },
  { title: "Spider-Man No Way Home", difficulty: "easy", popularity: "popular" },
  { title: "Top Gun Maverick", difficulty: "easy", popularity: "popular" },

  // ── EASY + NOT-SO-POPULAR ─────────────────────────────────────────────────
  { title: "Short Circuit", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Flubber", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Honey I Shrunk the Kids", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Casper", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Goonies", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Rookie of the Year", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Angels in the Outfield", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Free Willy", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Beethoven", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Richie Rich", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Dennis the Menace", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Little Giants", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Sandlot", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Rookie", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Space Jam", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Blank Check", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Monkey Trouble", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Indian in the Cupboard", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Fly Away Home", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Andre", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Mrs. Doubtfire", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Father of the Bride", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Groundhog Day", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Night at the Museum", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Elf", difficulty: "easy", popularity: "not-so-popular" },

  // ── EASY + RARELY-HEARD ───────────────────────────────────────────────────
  { title: "Paulie", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Bingo", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Dunston Checks In", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Harriet the Spy", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Angus", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Little Monsters", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Milo and Otis", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Benji", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Remote", difficulty: "easy", popularity: "rarely-heard" },
  { title: "The Adventures of Milo and Otis", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Prehysteria", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Blank Man", difficulty: "easy", popularity: "rarely-heard" },

  // ── MEDIUM + POPULAR ──────────────────────────────────────────────────────
  { title: "The Dark Knight", difficulty: "medium", popularity: "popular" },
  { title: "Inception", difficulty: "medium", popularity: "popular" },
  { title: "Interstellar", difficulty: "medium", popularity: "popular" },
  { title: "The Matrix", difficulty: "medium", popularity: "popular" },
  { title: "Gladiator", difficulty: "medium", popularity: "popular" },
  { title: "Schindler's List", difficulty: "medium", popularity: "popular" },
  { title: "The Godfather", difficulty: "medium", popularity: "popular" },
  { title: "Pulp Fiction", difficulty: "medium", popularity: "popular" },
  { title: "Fight Club", difficulty: "medium", popularity: "popular" },
  { title: "Goodfellas", difficulty: "medium", popularity: "popular" },
  { title: "The Shawshank Redemption", difficulty: "medium", popularity: "popular" },
  { title: "The Silence of the Lambs", difficulty: "medium", popularity: "popular" },
  { title: "No Country for Old Men", difficulty: "medium", popularity: "popular" },
  { title: "There Will Be Blood", difficulty: "medium", popularity: "popular" },
  { title: "Whiplash", difficulty: "medium", popularity: "popular" },
  { title: "Birdman", difficulty: "medium", popularity: "popular" },
  { title: "The Revenant", difficulty: "medium", popularity: "popular" },
  { title: "Mad Max Fury Road", difficulty: "medium", popularity: "popular" },
  { title: "Gravity", difficulty: "medium", popularity: "popular" },
  { title: "The Martian", difficulty: "medium", popularity: "popular" },
  { title: "Ex Machina", difficulty: "medium", popularity: "popular" },
  { title: "Her", difficulty: "medium", popularity: "popular" },
  { title: "Arrival", difficulty: "medium", popularity: "popular" },
  { title: "Dunkirk", difficulty: "medium", popularity: "popular" },
  { title: "1917", difficulty: "medium", popularity: "popular" },
  { title: "Parasite", difficulty: "medium", popularity: "popular" },
  { title: "Joker", difficulty: "medium", popularity: "popular" },
  { title: "Avengers Infinity War", difficulty: "medium", popularity: "popular" },
  { title: "Avengers Endgame", difficulty: "medium", popularity: "popular" },
  { title: "Black Widow", difficulty: "medium", popularity: "popular" },
  { title: "Shang-Chi", difficulty: "medium", popularity: "popular" },
  { title: "Eternals", difficulty: "medium", popularity: "popular" },
  { title: "Dune", difficulty: "medium", popularity: "popular" },
  { title: "The Batman", difficulty: "medium", popularity: "popular" },
  { title: "Everything Everywhere All at Once", difficulty: "medium", popularity: "popular" },
  { title: "The Whale", difficulty: "medium", popularity: "popular" },
  { title: "Tar", difficulty: "medium", popularity: "popular" },
  { title: "Oppenheimer", difficulty: "medium", popularity: "popular" },
  { title: "Barbie", difficulty: "medium", popularity: "popular" },
  { title: "Killers of the Flower Moon", difficulty: "medium", popularity: "popular" },
  { title: "Poor Things", difficulty: "medium", popularity: "popular" },
  { title: "American Fiction", difficulty: "medium", popularity: "popular" },
  { title: "Anatomy of a Fall", difficulty: "medium", popularity: "popular" },
  { title: "Zone of Interest", difficulty: "medium", popularity: "popular" },
  { title: "Past Lives", difficulty: "medium", popularity: "popular" },
  { title: "May December", difficulty: "medium", popularity: "popular" },
  { title: "Rustin", difficulty: "medium", popularity: "popular" },
  { title: "The Social Network", difficulty: "medium", popularity: "popular" },
  { title: "The Big Short", difficulty: "medium", popularity: "popular" },
  { title: "Wolf of Wall Street", difficulty: "medium", popularity: "popular" },
  { title: "Django Unchained", difficulty: "medium", popularity: "popular" },
  { title: "Inglourious Basterds", difficulty: "medium", popularity: "popular" },
  { title: "The Hateful Eight", difficulty: "medium", popularity: "popular" },
  { title: "Once Upon a Time in Hollywood", difficulty: "medium", popularity: "popular" },
  { title: "La La Land", difficulty: "medium", popularity: "popular" },
  { title: "Moonlight", difficulty: "medium", popularity: "popular" },
  { title: "Get Out", difficulty: "medium", popularity: "popular" },
  { title: "Us", difficulty: "medium", popularity: "popular" },
  { title: "A Quiet Place", difficulty: "medium", popularity: "popular" },
  { title: "Hereditary", difficulty: "medium", popularity: "popular" },
  { title: "Midsommar", difficulty: "medium", popularity: "popular" },
  { title: "It", difficulty: "medium", popularity: "popular" },
  { title: "Ready Player One", difficulty: "medium", popularity: "popular" },
  { title: "Tenet", difficulty: "medium", popularity: "popular" },
  { title: "Bohemian Rhapsody", difficulty: "medium", popularity: "popular" },
  { title: "Elvis", difficulty: "medium", popularity: "popular" },
  { title: "Nomadland", difficulty: "medium", popularity: "popular" },
  { title: "Promising Young Woman", difficulty: "medium", popularity: "popular" },
  { title: "The Power of the Dog", difficulty: "medium", popularity: "popular" },
  { title: "CODA", difficulty: "medium", popularity: "popular" },
  { title: "Silver Linings Playbook", difficulty: "medium", popularity: "popular" },
  { title: "American Hustle", difficulty: "medium", popularity: "popular" },
  { title: "Rocketman", difficulty: "medium", popularity: "popular" },
  { title: "Nightmare Alley", difficulty: "medium", popularity: "popular" },
  { title: "Licorice Pizza", difficulty: "medium", popularity: "popular" },
  { title: "The Grand Budapest Hotel", difficulty: "medium", popularity: "popular" },
  { title: "Knives Out", difficulty: "medium", popularity: "popular" },
  { title: "Glass Onion", difficulty: "medium", popularity: "popular" },
  { title: "Marriage Story", difficulty: "medium", popularity: "popular" },

  // ── MEDIUM + NOT-SO-POPULAR ───────────────────────────────────────────────
  { title: "Good Will Hunting", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Prestige", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Catch Me If You Can", difficulty: "medium", popularity: "not-so-popular" },
  { title: "A Beautiful Mind", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Rain Man", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Truman Show", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Eternal Sunshine of the Spotless Mind", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Being John Malkovich", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Adaptation", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Lost in Translation", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Royal Tenenbaums", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Rushmore", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Magnolia", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Boogie Nights", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Punch-Drunk Love", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Zodiac", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Prisoners", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Enemy", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Sicario", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Blade Runner 2049", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Annihilation", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Nice Guys", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Lighthouse", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Northman", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Spencer", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Belfast", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Lady Bird", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Frances Ha", difficulty: "medium", popularity: "not-so-popular" },
  { title: "20th Century Women", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Beale Street Could Talk", difficulty: "medium", popularity: "not-so-popular" },

  // ── MEDIUM + RARELY-HEARD ─────────────────────────────────────────────────
  { title: "Moon", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Coherence", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Primer", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Another Earth", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Sound of My Voice", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Safety Not Guaranteed", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Upstream Color", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Timecrimes", difficulty: "medium", popularity: "rarely-heard" },
  { title: "The One I Love", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Predestination", difficulty: "medium", popularity: "rarely-heard" },
  { title: "The Endless", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Resolution", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Spring", difficulty: "medium", popularity: "rarely-heard" },
  { title: "I Origins", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Synchronic", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Time Lapse", difficulty: "medium", popularity: "rarely-heard" },
  { title: "ARQ", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Infinity Chamber", difficulty: "medium", popularity: "rarely-heard" },

  // ── HARD + POPULAR ────────────────────────────────────────────────────────
  { title: "2001 A Space Odyssey", difficulty: "hard", popularity: "popular" },
  { title: "Apocalypse Now", difficulty: "hard", popularity: "popular" },
  { title: "Full Metal Jacket", difficulty: "hard", popularity: "popular" },
  { title: "A Clockwork Orange", difficulty: "hard", popularity: "popular" },
  { title: "Barry Lyndon", difficulty: "hard", popularity: "popular" },
  { title: "Eyes Wide Shut", difficulty: "hard", popularity: "popular" },
  { title: "The Shining", difficulty: "hard", popularity: "popular" },
  { title: "Chinatown", difficulty: "hard", popularity: "popular" },
  { title: "Network", difficulty: "hard", popularity: "popular" },
  { title: "All the President's Men", difficulty: "hard", popularity: "popular" },
  { title: "Dog Day Afternoon", difficulty: "hard", popularity: "popular" },
  { title: "Serpico", difficulty: "hard", popularity: "popular" },
  { title: "Taxi Driver", difficulty: "hard", popularity: "popular" },
  { title: "Raging Bull", difficulty: "hard", popularity: "popular" },
  { title: "The Deer Hunter", difficulty: "hard", popularity: "popular" },
  { title: "Coming Home", difficulty: "hard", popularity: "popular" },
  { title: "Nashville", difficulty: "hard", popularity: "popular" },
  { title: "McCabe and Mrs Miller", difficulty: "hard", popularity: "popular" },
  { title: "Days of Heaven", difficulty: "hard", popularity: "popular" },
  { title: "Badlands", difficulty: "hard", popularity: "popular" },
  { title: "Vertigo", difficulty: "hard", popularity: "popular" },
  { title: "Rear Window", difficulty: "hard", popularity: "popular" },

  // ── HARD + NOT-SO-POPULAR ─────────────────────────────────────────────────
  { title: "Repo Man", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Liquid Sky", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Eraserhead", difficulty: "hard", popularity: "not-so-popular" },
  { title: "El Topo", difficulty: "hard", popularity: "not-so-popular" },
  { title: "The Holy Mountain", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Pink Flamingos", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Phantom of the Paradise", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Times Square", difficulty: "hard", popularity: "not-so-popular" },
  { title: "The Wanderers", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Over the Edge", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Ladies and Gentlemen the Fabulous Stains", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Smithereens", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Stranger Than Paradise", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Permanent Vacation", difficulty: "hard", popularity: "not-so-popular" },
  { title: "In the Soup", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Slacker", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Waking Life", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Barton Fink", difficulty: "hard", popularity: "not-so-popular" },

  // ── HARD + RARELY-HEARD ───────────────────────────────────────────────────
  { title: "Wavelength", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Empire", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Chelsea Girls", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Scorpio Rising", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Flaming Creatures", difficulty: "hard", popularity: "rarely-heard" },
  { title: "The Passion of Joan of Arc", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Fireworks", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Meshes of the Afternoon", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Ballet Mecanique", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Man with a Movie Camera", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Nosferatu", difficulty: "hard", popularity: "rarely-heard" },
  { title: "The Cabinet of Dr Caligari", difficulty: "hard", popularity: "rarely-heard" },

  // ── EASY + POPULAR (additional) ──────────────────────────────────────────
  { title: "Jurassic World", difficulty: "easy", popularity: "popular" },
  { title: "Jurassic World Fallen Kingdom", difficulty: "easy", popularity: "popular" },
  { title: "Jurassic World Dominion", difficulty: "easy", popularity: "popular" },
  { title: "The Mummy", difficulty: "easy", popularity: "popular" },
  { title: "Indiana Jones", difficulty: "easy", popularity: "popular" },
  { title: "Indiana Jones and the Temple of Doom", difficulty: "easy", popularity: "popular" },
  { title: "Indiana Jones and the Last Crusade", difficulty: "easy", popularity: "popular" },
  { title: "Die Hard", difficulty: "easy", popularity: "popular" },
  { title: "Die Hard with a Vengeance", difficulty: "easy", popularity: "popular" },
  { title: "Lethal Weapon", difficulty: "easy", popularity: "popular" },
  { title: "Ocean's Eleven", difficulty: "easy", popularity: "popular" },
  { title: "Ocean's Twelve", difficulty: "easy", popularity: "popular" },
  { title: "Ocean's Thirteen", difficulty: "easy", popularity: "popular" },
  { title: "National Treasure", difficulty: "easy", popularity: "popular" },
  { title: "Con Air", difficulty: "easy", popularity: "popular" },
  { title: "The Rock", difficulty: "easy", popularity: "popular" },
  { title: "Face Off", difficulty: "easy", popularity: "popular" },
  { title: "Armageddon", difficulty: "easy", popularity: "popular" },
  { title: "Deep Impact", difficulty: "easy", popularity: "popular" },
  { title: "Twister", difficulty: "easy", popularity: "popular" },
  { title: "The Day After Tomorrow", difficulty: "easy", popularity: "popular" },
  { title: "2012", difficulty: "easy", popularity: "popular" },
  { title: "San Andreas", difficulty: "easy", popularity: "popular" },
  { title: "Independence Day", difficulty: "easy", popularity: "popular" },
  { title: "World War Z", difficulty: "easy", popularity: "popular" },
  { title: "I Am Legend", difficulty: "easy", popularity: "popular" },
  { title: "Suicide Squad", difficulty: "easy", popularity: "popular" },
  { title: "Birds of Prey", difficulty: "easy", popularity: "popular" },
  { title: "The Suicide Squad", difficulty: "easy", popularity: "popular" },
  { title: "Mortal Kombat", difficulty: "easy", popularity: "popular" },
  { title: "G.I. Joe", difficulty: "easy", popularity: "popular" },
  { title: "Transformers Dark of the Moon", difficulty: "easy", popularity: "popular" },
  { title: "Transformers Age of Extinction", difficulty: "easy", popularity: "popular" },
  { title: "Bumblebee", difficulty: "easy", popularity: "popular" },
  { title: "Ghostbusters", difficulty: "easy", popularity: "popular" },
  { title: "Ghostbusters Afterlife", difficulty: "easy", popularity: "popular" },
  { title: "Ghostbusters Frozen Empire", difficulty: "easy", popularity: "popular" },
  { title: "Maleficent", difficulty: "easy", popularity: "popular" },
  { title: "Cinderella", difficulty: "easy", popularity: "popular" },
  { title: "Mulan", difficulty: "easy", popularity: "popular" },
  { title: "Raya and the Last Dragon", difficulty: "easy", popularity: "popular" },
  { title: "Turning Red", difficulty: "easy", popularity: "popular" },
  { title: "Lightyear", difficulty: "easy", popularity: "popular" },
  { title: "Wish", difficulty: "easy", popularity: "popular" },
  { title: "Inside Out 2", difficulty: "easy", popularity: "popular" },
  { title: "Despicable Me 4", difficulty: "easy", popularity: "popular" },
  { title: "Moana 2", difficulty: "easy", popularity: "popular" },
  { title: "Mufasa The Lion King", difficulty: "easy", popularity: "popular" },
  { title: "Wicked", difficulty: "easy", popularity: "popular" },
  { title: "Deadpool and Wolverine", difficulty: "easy", popularity: "popular" },
  { title: "Alien Romulus", difficulty: "easy", popularity: "popular" },
  { title: "Kingdom of the Planet of the Apes", difficulty: "easy", popularity: "popular" },
  { title: "Transformers One", difficulty: "easy", popularity: "popular" },
  { title: "Dune", difficulty: "easy", popularity: "popular" },
  { title: "Dune Part Two", difficulty: "easy", popularity: "popular" },
  { title: "James Bond", difficulty: "easy", popularity: "popular" },
  { title: "Goldfinger", difficulty: "easy", popularity: "popular" },
  { title: "Casino Royale", difficulty: "easy", popularity: "popular" },
  { title: "Skyfall", difficulty: "easy", popularity: "popular" },
  { title: "No Time to Die", difficulty: "easy", popularity: "popular" },
  { title: "Rush Hour", difficulty: "easy", popularity: "popular" },
  { title: "Rush Hour 2", difficulty: "easy", popularity: "popular" },
  { title: "The Mask of Zorro", difficulty: "easy", popularity: "popular" },
  { title: "Enchanted", difficulty: "easy", popularity: "popular" },
  { title: "Disenchanted", difficulty: "easy", popularity: "popular" },
  { title: "The Jungle Book 2016", difficulty: "easy", popularity: "popular" },
  { title: "Lilo and Stitch", difficulty: "easy", popularity: "popular" },
  { title: "Bambi", difficulty: "easy", popularity: "popular" },
  { title: "Dumbo", difficulty: "easy", popularity: "popular" },
  { title: "Pinocchio", difficulty: "easy", popularity: "popular" },
  { title: "Peter Pan", difficulty: "easy", popularity: "popular" },
  { title: "Alice in Wonderland", difficulty: "easy", popularity: "popular" },
  { title: "Sleeping Beauty", difficulty: "easy", popularity: "popular" },
  { title: "Snow White", difficulty: "easy", popularity: "popular" },
  { title: "101 Dalmatians", difficulty: "easy", popularity: "popular" },
  { title: "The Hunchback of Notre Dame", difficulty: "easy", popularity: "popular" },
  { title: "Hercules", difficulty: "easy", popularity: "popular" },
  { title: "Pocahontas", difficulty: "easy", popularity: "popular" },
  { title: "Tarzan", difficulty: "easy", popularity: "popular" },
  { title: "Atlantis The Lost Empire", difficulty: "easy", popularity: "popular" },
  { title: "Lilo and Stitch 2", difficulty: "easy", popularity: "popular" },
  { title: "Bolt", difficulty: "easy", popularity: "popular" },
  { title: "The Princess and the Frog", difficulty: "easy", popularity: "popular" },
  { title: "Winnie the Pooh", difficulty: "easy", popularity: "popular" },
  { title: "Ralph Breaks the Internet", difficulty: "easy", popularity: "popular" },
  { title: "Onward", difficulty: "easy", popularity: "popular" },
  { title: "Soul", difficulty: "easy", popularity: "popular" },
  { title: "Luca", difficulty: "easy", popularity: "popular" },
  { title: "Elemental", difficulty: "easy", popularity: "popular" },
  { title: "The Good Dinosaur", difficulty: "easy", popularity: "popular" },
  { title: "Monsters Inc", difficulty: "easy", popularity: "popular" },
  { title: "Monsters University", difficulty: "easy", popularity: "popular" },
  { title: "The Emoji Movie", difficulty: "easy", popularity: "popular" },
  { title: "The Angry Birds Movie", difficulty: "easy", popularity: "popular" },
  { title: "Puss in Boots", difficulty: "easy", popularity: "popular" },
  { title: "Shrek 2", difficulty: "easy", popularity: "popular" },
  { title: "Shrek Forever After", difficulty: "easy", popularity: "popular" },
  { title: "Kung Fu Panda 2", difficulty: "easy", popularity: "popular" },
  { title: "Kung Fu Panda 3", difficulty: "easy", popularity: "popular" },

  // ── EASY + NOT-SO-POPULAR (additional) ───────────────────────────────────
  { title: "Problem Child", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Big", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Jack", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Bicentennial Man", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Patch Adams", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Fluke", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Air Bud", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Mighty Ducks", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Mighty Ducks", difficulty: "easy", popularity: "not-so-popular" },
  { title: "D2 The Mighty Ducks", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Rookie of the Year 2", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Little Big League", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Air Up There", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Santa Clause", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Jingle All the Way", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Pagemaster", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Richie Rich 2", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Kids in the Hall", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Big Fat Liar", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Agent Cody Banks", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Spy Kids", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Spy Kids 2", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Cat in the Hat", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Grinch", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Cheaper by the Dozen", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Freaky Friday", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Parent Trap", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Herbie Fully Loaded", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Bedknobs and Broomsticks", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Love Bug", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Escape to Witch Mountain", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Black Hole", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Tron", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Tron Legacy", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Flight of the Navigator", difficulty: "easy", popularity: "not-so-popular" },
  { title: "My Neighbor Totoro", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Spirited Away", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Princess Mononoke", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Howls Moving Castle", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Castle in the Sky", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Kiki's Delivery Service", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Nausicaa of the Valley of the Wind", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Lupin the Third Castle of Cagliostro", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Porco Rosso", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Wind Rises", difficulty: "easy", popularity: "not-so-popular" },
  { title: "When Marnie Was There", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Wolf Children", difficulty: "easy", popularity: "not-so-popular" },
  { title: "The Boy and the Heron", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Summer Wars", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Your Name", difficulty: "easy", popularity: "not-so-popular" },
  { title: "A Silent Voice", difficulty: "easy", popularity: "not-so-popular" },

  // ── EASY + RARELY-HEARD (additional) ─────────────────────────────────────
  { title: "Dot and the Kangaroo", difficulty: "easy", popularity: "rarely-heard" },
  { title: "The Adventures of Ichabod and Mr Toad", difficulty: "easy", popularity: "rarely-heard" },
  { title: "The Great Mouse Detective", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Oliver and Company", difficulty: "easy", popularity: "rarely-heard" },
  { title: "The Rescuers", difficulty: "easy", popularity: "rarely-heard" },
  { title: "The Fox and the Hound", difficulty: "easy", popularity: "rarely-heard" },
  { title: "The Aristocats", difficulty: "easy", popularity: "rarely-heard" },
  { title: "The Sword in the Stone", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Saludos Amigos", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Fun and Fancy Free", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Make Mine Music", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Melody Time", difficulty: "easy", popularity: "rarely-heard" },
  { title: "The Three Caballeros", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Bambi 2", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Cinderella 3 A Twist in Time", difficulty: "easy", popularity: "rarely-heard" },
  { title: "The Little Mermaid 2", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Beauty and the Beast Enchanted Christmas", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Aladdin and the King of Thieves", difficulty: "easy", popularity: "rarely-heard" },
  { title: "The Return of Jafar", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Mulan 2", difficulty: "easy", popularity: "rarely-heard" },

  // ── MEDIUM + POPULAR (additional) ────────────────────────────────────────
  { title: "Spotlight", difficulty: "medium", popularity: "popular" },
  { title: "The Artist", difficulty: "medium", popularity: "popular" },
  { title: "The Hurt Locker", difficulty: "medium", popularity: "popular" },
  { title: "Crash", difficulty: "medium", popularity: "popular" },
  { title: "Million Dollar Baby", difficulty: "medium", popularity: "popular" },
  { title: "Chicago", difficulty: "medium", popularity: "popular" },
  { title: "Braveheart", difficulty: "medium", popularity: "popular" },
  { title: "American Beauty", difficulty: "medium", popularity: "popular" },
  { title: "Shakespeare in Love", difficulty: "medium", popularity: "popular" },
  { title: "Argo", difficulty: "medium", popularity: "popular" },
  { title: "12 Years a Slave", difficulty: "medium", popularity: "popular" },
  { title: "The Theory of Everything", difficulty: "medium", popularity: "popular" },
  { title: "The Imitation Game", difficulty: "medium", popularity: "popular" },
  { title: "Bridge of Spies", difficulty: "medium", popularity: "popular" },
  { title: "Philadelphia", difficulty: "medium", popularity: "popular" },
  { title: "The Pianist", difficulty: "medium", popularity: "popular" },
  { title: "Life is Beautiful", difficulty: "medium", popularity: "popular" },
  { title: "Cinema Paradiso", difficulty: "medium", popularity: "popular" },
  { title: "Conclave", difficulty: "medium", popularity: "popular" },
  { title: "Emilia Perez", difficulty: "medium", popularity: "popular" },
  { title: "The Brutalist", difficulty: "medium", popularity: "popular" },
  { title: "Anora", difficulty: "medium", popularity: "popular" },
  { title: "A Complete Unknown", difficulty: "medium", popularity: "popular" },
  { title: "Nosferatu 2024", difficulty: "medium", popularity: "popular" },
  { title: "Wicked 2024", difficulty: "medium", popularity: "popular" },
  { title: "Gladiator II", difficulty: "medium", popularity: "popular" },
  { title: "Alien", difficulty: "medium", popularity: "popular" },
  { title: "Aliens", difficulty: "medium", popularity: "popular" },
  { title: "Predator", difficulty: "medium", popularity: "popular" },
  { title: "The Terminator 2", difficulty: "medium", popularity: "popular" },
  { title: "Robocop", difficulty: "medium", popularity: "popular" },
  { title: "Total Recall", difficulty: "medium", popularity: "popular" },
  { title: "Basic Instinct", difficulty: "medium", popularity: "popular" },
  { title: "The Truman Show", difficulty: "medium", popularity: "popular" },
  { title: "As Good as It Gets", difficulty: "medium", popularity: "popular" },
  { title: "American History X", difficulty: "medium", popularity: "popular" },
  { title: "Se7en", difficulty: "medium", popularity: "popular" },
  { title: "Silence of the Lambs", difficulty: "medium", popularity: "popular" },
  { title: "Forrest Gump", difficulty: "medium", popularity: "popular" },
  { title: "Philadelphia", difficulty: "medium", popularity: "popular" },
  { title: "The Green Mile", difficulty: "medium", popularity: "popular" },
  { title: "Cast Away", difficulty: "medium", popularity: "popular" },
  { title: "The Da Vinci Code", difficulty: "medium", popularity: "popular" },
  { title: "Angels and Demons", difficulty: "medium", popularity: "popular" },
  { title: "Inferno", difficulty: "medium", popularity: "popular" },
  { title: "Jumanji", difficulty: "medium", popularity: "popular" },
  { title: "Jumanji Welcome to the Jungle", difficulty: "medium", popularity: "popular" },
  { title: "Jumanji The Next Level", difficulty: "medium", popularity: "popular" },
  { title: "Night at the Museum 2", difficulty: "medium", popularity: "popular" },
  { title: "Night at the Museum Secret of the Tomb", difficulty: "medium", popularity: "popular" },
  { title: "Ace Ventura Pet Detective", difficulty: "medium", popularity: "popular" },
  { title: "The Truman Show", difficulty: "medium", popularity: "popular" },
  { title: "Liar Liar", difficulty: "medium", popularity: "popular" },
  { title: "Bruce Almighty", difficulty: "medium", popularity: "popular" },
  { title: "Eternal Sunshine of the Spotless Mind", difficulty: "medium", popularity: "popular" },
  { title: "Adaptation", difficulty: "medium", popularity: "popular" },
  { title: "Confessions of a Dangerous Mind", difficulty: "medium", popularity: "popular" },
  { title: "Charlie and the Chocolate Factory", difficulty: "medium", popularity: "popular" },
  { title: "Edward Scissorhands", difficulty: "medium", popularity: "popular" },
  { title: "Big Eyes", difficulty: "medium", popularity: "popular" },
  { title: "Ed Wood", difficulty: "medium", popularity: "popular" },
  { title: "Beetlejuice", difficulty: "medium", popularity: "popular" },
  { title: "Beetlejuice Beetlejuice", difficulty: "medium", popularity: "popular" },
  { title: "Miss Peregrine's Home for Peculiar Children", difficulty: "medium", popularity: "popular" },
  { title: "Nightmare Before Christmas", difficulty: "medium", popularity: "popular" },
  { title: "Coraline", difficulty: "medium", popularity: "popular" },
  { title: "Paranorman", difficulty: "medium", popularity: "popular" },
  { title: "Frankenweenie", difficulty: "medium", popularity: "popular" },
  { title: "The Boxtrolls", difficulty: "medium", popularity: "popular" },
  { title: "Kubo and the Two Strings", difficulty: "medium", popularity: "popular" },
  { title: "Missing Link", difficulty: "medium", popularity: "popular" },
  { title: "I Robot", difficulty: "medium", popularity: "popular" },
  { title: "A.I. Artificial Intelligence", difficulty: "medium", popularity: "popular" },
  { title: "Minority Report", difficulty: "medium", popularity: "popular" },
  { title: "War of the Worlds", difficulty: "medium", popularity: "popular" },
  { title: "Lincoln", difficulty: "medium", popularity: "popular" },
  { title: "Munich", difficulty: "medium", popularity: "popular" },
  { title: "Saving Private Ryan", difficulty: "medium", popularity: "popular" },
  { title: "Raiders of the Lost Ark", difficulty: "medium", popularity: "popular" },
  { title: "Jaws", difficulty: "medium", popularity: "popular" },
  { title: "Close Encounters of the Third Kind", difficulty: "medium", popularity: "popular" },
  { title: "ET The Extra Terrestrial", difficulty: "medium", popularity: "popular" },
  { title: "Schindler's List", difficulty: "medium", popularity: "popular" },
  { title: "Amistad", difficulty: "medium", popularity: "popular" },
  { title: "The Color Purple", difficulty: "medium", popularity: "popular" },
  { title: "Empire of the Sun", difficulty: "medium", popularity: "popular" },
  { title: "Always", difficulty: "medium", popularity: "popular" },
  { title: "Hook", difficulty: "medium", popularity: "popular" },
  { title: "Artificial Intelligence", difficulty: "medium", popularity: "popular" },
  { title: "Conclave 2024", difficulty: "medium", popularity: "popular" },
  { title: "Flow 2024", difficulty: "medium", popularity: "popular" },
  { title: "Hard Truths", difficulty: "medium", popularity: "popular" },
  { title: "Maria 2024", difficulty: "medium", popularity: "popular" },
  { title: "September 5", difficulty: "medium", popularity: "popular" },
  { title: "The Room Next Door", difficulty: "medium", popularity: "popular" },
  { title: "The Substance", difficulty: "medium", popularity: "popular" },
  { title: "Queer", difficulty: "medium", popularity: "popular" },
  { title: "On Swift Horses", difficulty: "medium", popularity: "popular" },
  { title: "Love Me", difficulty: "medium", popularity: "popular" },

  // ── MEDIUM + NOT-SO-POPULAR (additional) ─────────────────────────────────
  { title: "Phantom Thread", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Darkest Hour", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Three Billboards Outside Ebbing Missouri", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Shape of Water", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Minari", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Judas and the Black Messiah", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Father", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Sound of Metal", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Mank", difficulty: "medium", popularity: "not-so-popular" },
  { title: "I'm Thinking of Ending Things", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Pieces of a Woman", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Midnight Sky", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Mauritanian", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Cherry", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Hillbilly Elegy", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Malcolm and Marie", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Dick Johnson Is Dead", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Quo Vadis Aida", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Dig", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Two Days One Night", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Son of Saul", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Mustang", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Embrace of the Serpent", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Loveless", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Capernaum", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Cold War", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Never Look Away", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Les Miserables 2019", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Portrait of a Lady on Fire", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Corpus Christi", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Gagarine", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Summer of Soul", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Writing with Fire", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Attica", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Drive My Car", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Flee", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Ascension", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Parallel Mothers", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Hand of God", difficulty: "medium", popularity: "not-so-popular" },
  { title: "A Hero", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Great Freedom", difficulty: "medium", popularity: "not-so-popular" },
  { title: "All Quiet on the Western Front", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Argentina 1985", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Quiet Girl", difficulty: "medium", popularity: "not-so-popular" },
  { title: "EO", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Corsage", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Le Otto Montagne", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Saint Omer", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Triangle of Sadness", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Aftersun", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Decision to Leave", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Holy Spider", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Return to Seoul", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Tori and Lokita", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Rimini", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Eight Mountains", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Showing Up", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Old Oak", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Fallen Leaves", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Monster 2023", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Ice Merchants", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Priscilla", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Banel and Adama", difficulty: "medium", popularity: "not-so-popular" },
  { title: "How to Have Sex", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Trenque Lauquen", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Passages", difficulty: "medium", popularity: "not-so-popular" },
  { title: "A Haunting in Venice", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Maestro", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Saltburn", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Origin", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Nyad", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Cassandro", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Dream Scenario", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Quiz Lady", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Holdovers", difficulty: "medium", popularity: "not-so-popular" },
  { title: "All of Us Strangers", difficulty: "medium", popularity: "not-so-popular" },
  { title: "The Zone of Interest", difficulty: "medium", popularity: "not-so-popular" },

  // ── MEDIUM + RARELY-HEARD (additional) ───────────────────────────────────
  { title: "Sans Soleil", difficulty: "medium", popularity: "rarely-heard" },
  { title: "The Gleaners and I", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Waltz with Bashir", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Stories We Tell", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Hoop Dreams", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Harlan County USA", difficulty: "medium", popularity: "rarely-heard" },
  { title: "The Act of Killing", difficulty: "medium", popularity: "rarely-heard" },
  { title: "The Look of Silence", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Shoah", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Grey Gardens", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Grizzly Man", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Capturing the Friedmans", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Titticut Follies", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Salesman", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Crumb", difficulty: "medium", popularity: "rarely-heard" },
  { title: "American Movie", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Dark Days", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Roger and Me", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Bowling for Columbine", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Fahrenheit 9/11", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Super Size Me", difficulty: "medium", popularity: "rarely-heard" },
  { title: "An Inconvenient Truth", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Sicko", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Searching for Sugar Man", difficulty: "medium", popularity: "rarely-heard" },
  { title: "The Imposter", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Blackfish", difficulty: "medium", popularity: "rarely-heard" },
  { title: "20 Feet from Stardom", difficulty: "medium", popularity: "rarely-heard" },
  { title: "The Square 2017", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Faces Places", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Icarus", difficulty: "medium", popularity: "rarely-heard" },

  // ── HARD + POPULAR (additional) ───────────────────────────────────────────
  { title: "Citizen Kane", difficulty: "hard", popularity: "popular" },
  { title: "Casablanca", difficulty: "hard", popularity: "popular" },
  { title: "The Wizard of Oz", difficulty: "hard", popularity: "popular" },
  { title: "Sunset Boulevard", difficulty: "hard", popularity: "popular" },
  { title: "All About Eve", difficulty: "hard", popularity: "popular" },
  { title: "Singin' in the Rain", difficulty: "hard", popularity: "popular" },
  { title: "Roman Holiday", difficulty: "hard", popularity: "popular" },
  { title: "Breakfast at Tiffany's", difficulty: "hard", popularity: "popular" },
  { title: "My Fair Lady", difficulty: "hard", popularity: "popular" },
  { title: "Lawrence of Arabia", difficulty: "hard", popularity: "popular" },
  { title: "Doctor Zhivago", difficulty: "hard", popularity: "popular" },
  { title: "Ben-Hur", difficulty: "hard", popularity: "popular" },
  { title: "The Sound of Music", difficulty: "hard", popularity: "popular" },
  { title: "West Side Story", difficulty: "hard", popularity: "popular" },
  { title: "On the Waterfront", difficulty: "hard", popularity: "popular" },
  { title: "From Here to Eternity", difficulty: "hard", popularity: "popular" },
  { title: "Marty", difficulty: "hard", popularity: "popular" },
  { title: "Around the World in 80 Days", difficulty: "hard", popularity: "popular" },
  { title: "The Greatest Show on Earth", difficulty: "hard", popularity: "popular" },
  { title: "An American in Paris", difficulty: "hard", popularity: "popular" },
  { title: "All About Eve", difficulty: "hard", popularity: "popular" },
  { title: "Gentleman's Agreement", difficulty: "hard", popularity: "popular" },
  { title: "The Best Years of Our Lives", difficulty: "hard", popularity: "popular" },
  { title: "Going My Way", difficulty: "hard", popularity: "popular" },
  { title: "Casablanca Classic", difficulty: "hard", popularity: "popular" },
  { title: "How Green Was My Valley", difficulty: "hard", popularity: "popular" },
  { title: "Rebecca", difficulty: "hard", popularity: "popular" },
  { title: "Gone with the Wind", difficulty: "hard", popularity: "popular" },
  { title: "You Can't Take It with You", difficulty: "hard", popularity: "popular" },
  { title: "The Life of Emile Zola", difficulty: "hard", popularity: "popular" },
  { title: "The Great Ziegfeld", difficulty: "hard", popularity: "popular" },
  { title: "Mutiny on the Bounty", difficulty: "hard", popularity: "popular" },
  { title: "It Happened One Night", difficulty: "hard", popularity: "popular" },
  { title: "Cavalcade", difficulty: "hard", popularity: "popular" },
  { title: "Grand Hotel", difficulty: "hard", popularity: "popular" },
  { title: "Cimarron", difficulty: "hard", popularity: "popular" },
  { title: "All Quiet on the Western Front Classic", difficulty: "hard", popularity: "popular" },
  { title: "Broadway Melody", difficulty: "hard", popularity: "popular" },
  { title: "Wings", difficulty: "hard", popularity: "popular" },
  { title: "Lawrence of Arabia Classic", difficulty: "hard", popularity: "popular" },
  { title: "The Bridge on the River Kwai", difficulty: "hard", popularity: "popular" },
  { title: "Around the World in 80 Days 1956", difficulty: "hard", popularity: "popular" },
  { title: "Gigi", difficulty: "hard", popularity: "popular" },
  { title: "The Apartment", difficulty: "hard", popularity: "popular" },
  { title: "West Side Story 1961", difficulty: "hard", popularity: "popular" },
  { title: "Tom Jones", difficulty: "hard", popularity: "popular" },
  { title: "My Fair Lady 1964", difficulty: "hard", popularity: "popular" },
  { title: "The Sound of Music 1965", difficulty: "hard", popularity: "popular" },
  { title: "A Man for All Seasons", difficulty: "hard", popularity: "popular" },
  { title: "Oliver!", difficulty: "hard", popularity: "popular" },
  { title: "Midnight Cowboy", difficulty: "hard", popularity: "popular" },

  // ── HARD + NOT-SO-POPULAR (additional) ────────────────────────────────────
  { title: "Amarcord", difficulty: "hard", popularity: "not-so-popular" },
  { title: "8 1/2", difficulty: "hard", popularity: "not-so-popular" },
  { title: "La Dolce Vita", difficulty: "hard", popularity: "not-so-popular" },
  { title: "The Bicycle Thief", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Open City", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Paisà", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Germany Year Zero", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Umberto D", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Shoeshine", difficulty: "hard", popularity: "not-so-popular" },
  { title: "L'Avventura", difficulty: "hard", popularity: "not-so-popular" },
  { title: "L'Eclisse", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Red Desert", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Breathless", difficulty: "hard", popularity: "not-so-popular" },
  { title: "The 400 Blows", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Jules and Jim", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Shoot the Piano Player", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Contempt", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Band of Outsiders", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Vivre Sa Vie", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Alphaville", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Weekend", difficulty: "hard", popularity: "not-so-popular" },
  { title: "The Wild Child", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Cleo from 5 to 7", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Le Bonheur", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Vagabond", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Hiroshima Mon Amour", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Last Year at Marienbad", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Au Hasard Balthazar", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Mouchette", difficulty: "hard", popularity: "not-so-popular" },
  { title: "A Man Escaped", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Pickpocket", difficulty: "hard", popularity: "not-so-popular" },
  { title: "L'Age d'Or", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Un Chien Andalou", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Los Olvidados", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Viridiana", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Belle de Jour", difficulty: "hard", popularity: "not-so-popular" },
  { title: "The Discreet Charm of the Bourgeoisie", difficulty: "hard", popularity: "not-so-popular" },
  { title: "The Exterminating Angel", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Simon of the Desert", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Nazarin", difficulty: "hard", popularity: "not-so-popular" },

  // ── HARD + RARELY-HEARD (additional) ──────────────────────────────────────
  { title: "Jeanne Dielman", difficulty: "hard", popularity: "rarely-heard" },
  { title: "News from Home", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Toute une nuit", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Je tu il elle", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Meetings with Anna", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Golden Eighties", difficulty: "hard", popularity: "rarely-heard" },
  { title: "La Captive", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Tout pres de moi", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Germinal", difficulty: "hard", popularity: "rarely-heard" },
  { title: "The Story of Adele H", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Day for Night", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Small Change", difficulty: "hard", popularity: "rarely-heard" },
  { title: "The Man Who Loved Women", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Love on the Run", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Stolen Kisses", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Bed and Board", difficulty: "hard", popularity: "rarely-heard" },
  { title: "The Soft Skin", difficulty: "hard", popularity: "rarely-heard" },
  { title: "The Bride Wore Black", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Mississippi Mermaid", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Such a Gorgeous Kid Like Me", difficulty: "hard", popularity: "rarely-heard" },
  { title: "The Green Room", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Two English Girls", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Anne and Muriel", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Wild Reeds", difficulty: "hard", popularity: "rarely-heard" },
  { title: "L'Humanite", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Time Out", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Rosetta", difficulty: "hard", popularity: "rarely-heard" },
  { title: "The Son 2002", difficulty: "hard", popularity: "rarely-heard" },
  { title: "The Child 2005", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Bicycle Thieves", difficulty: "hard", popularity: "rarely-heard" },

  // ── EASY + POPULAR (final additions) ─────────────────────────────────────
  { title: "Jurassic Park 3", difficulty: "easy", popularity: "popular" },
  { title: "The Lost World Jurassic Park", difficulty: "easy", popularity: "popular" },
  { title: "King Kong", difficulty: "easy", popularity: "popular" },
  { title: "Godzilla", difficulty: "easy", popularity: "popular" },
  { title: "Pacific Rim", difficulty: "easy", popularity: "popular" },
  { title: "Pacific Rim Uprising", difficulty: "easy", popularity: "popular" },
  { title: "Godzilla vs Kong", difficulty: "easy", popularity: "popular" },
  { title: "Godzilla Minus One", difficulty: "easy", popularity: "popular" },
  { title: "Monkey Man", difficulty: "easy", popularity: "popular" },
  { title: "John Wick", difficulty: "easy", popularity: "popular" },
  { title: "John Wick Chapter 2", difficulty: "easy", popularity: "popular" },
  { title: "John Wick Chapter 3", difficulty: "easy", popularity: "popular" },
  { title: "John Wick Chapter 4", difficulty: "easy", popularity: "popular" },
  { title: "The Equalizer", difficulty: "easy", popularity: "popular" },
  { title: "The Equalizer 2", difficulty: "easy", popularity: "popular" },
  { title: "Taken", difficulty: "easy", popularity: "popular" },
  { title: "Taken 2", difficulty: "easy", popularity: "popular" },
  { title: "Jack Reacher", difficulty: "easy", popularity: "popular" },
  { title: "Bullet Train", difficulty: "easy", popularity: "popular" },
  { title: "The Gray Man", difficulty: "easy", popularity: "popular" },
];
