const MOVIES_TOLLYWOOD = [
  // ── EASY + POPULAR (TELUGU) ───────────────────────────────────────────────
  { title: "RRR", difficulty: "easy", popularity: "popular" },
  { title: "Baahubali The Beginning", difficulty: "easy", popularity: "popular" },
  { title: "Baahubali The Conclusion", difficulty: "easy", popularity: "popular" },
  { title: "Pushpa The Rise", difficulty: "easy", popularity: "popular" },
  { title: "Pushpa The Rule", difficulty: "easy", popularity: "popular" },
  { title: "Arjun Reddy", difficulty: "easy", popularity: "popular" },
  { title: "Magadheera", difficulty: "easy", popularity: "popular" },
  { title: "Eega", difficulty: "easy", popularity: "popular" },
  { title: "Vikram Vedha Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Temper", difficulty: "easy", popularity: "popular" },
  { title: "Gabbar Singh", difficulty: "easy", popularity: "popular" },
  { title: "Julayi", difficulty: "easy", popularity: "popular" },
  { title: "Dookudu", difficulty: "easy", popularity: "popular" },
  { title: "Brindavanam", difficulty: "easy", popularity: "popular" },
  { title: "Nenu Local", difficulty: "easy", popularity: "popular" },
  { title: "Fidaa", difficulty: "easy", popularity: "popular" },
  { title: "Geetha Govindam", difficulty: "easy", popularity: "popular" },
  { title: "Bheeshma", difficulty: "easy", popularity: "popular" },
  { title: "Ala Vaikunthapurramuloo", difficulty: "easy", popularity: "popular" },
  { title: "DJ Duvvada Jagannadham", difficulty: "easy", popularity: "popular" },
  { title: "Sarrainodu", difficulty: "easy", popularity: "popular" },
  { title: "Race Gurram", difficulty: "easy", popularity: "popular" },
  { title: "S/O Satyamurthy", difficulty: "easy", popularity: "popular" },
  { title: "Srimanthudu", difficulty: "easy", popularity: "popular" },
  { title: "Sye Raa Narasimha Reddy", difficulty: "easy", popularity: "popular" },
  { title: "Maharshi", difficulty: "easy", popularity: "popular" },
  { title: "Bharat Ane Nenu", difficulty: "easy", popularity: "popular" },
  { title: "Businessman", difficulty: "easy", popularity: "popular" },
  { title: "Mirchi", difficulty: "easy", popularity: "popular" },
  { title: "Seethamma Vakitlo Sirimalle Chettu", difficulty: "easy", popularity: "popular" },
  { title: "Waltair Veerayya", difficulty: "easy", popularity: "popular" },
  { title: "Veera Simha Reddy", difficulty: "easy", popularity: "popular" },
  { title: "Aadavallu Meeku Johaarlu", difficulty: "easy", popularity: "popular" },
  { title: "Hanuman 2024", difficulty: "easy", popularity: "popular" },
  { title: "Bro Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Skanda", difficulty: "easy", popularity: "popular" },
  { title: "Guntur Kaaram", difficulty: "easy", popularity: "popular" },
  { title: "Tillu Square", difficulty: "easy", popularity: "popular" },
  { title: "Devara", difficulty: "easy", popularity: "popular" },
  { title: "Saindhav", difficulty: "easy", popularity: "popular" },

  // ── EASY + POPULAR (TAMIL) ────────────────────────────────────────────────
  { title: "Mersal", difficulty: "easy", popularity: "popular" },
  { title: "96", difficulty: "easy", popularity: "popular" },
  { title: "Thuppakki", difficulty: "easy", popularity: "popular" },
  { title: "Enthiran", difficulty: "easy", popularity: "popular" },
  { title: "Kaithi", difficulty: "easy", popularity: "popular" },
  { title: "Vikram", difficulty: "easy", popularity: "popular" },
  { title: "Varisu", difficulty: "easy", popularity: "popular" },
  { title: "Thunivu", difficulty: "easy", popularity: "popular" },
  { title: "Master", difficulty: "easy", popularity: "popular" },
  { title: "Doctor", difficulty: "easy", popularity: "popular" },
  { title: "Valimai", difficulty: "easy", popularity: "popular" },
  { title: "Beast", difficulty: "easy", popularity: "popular" },
  { title: "Etharkkum Thunindhavan", difficulty: "easy", popularity: "popular" },
  { title: "Jai Bhim", difficulty: "easy", popularity: "popular" },
  { title: "Soorarai Pottru", difficulty: "easy", popularity: "popular" },
  { title: "Asuran", difficulty: "easy", popularity: "popular" },
  { title: "Pariyerum Perumal", difficulty: "easy", popularity: "popular" },
  { title: "Sarpatta Parambarai", difficulty: "easy", popularity: "popular" },
  { title: "Super Deluxe", difficulty: "easy", popularity: "popular" },
  { title: "Thalapathi", difficulty: "easy", popularity: "popular" },
  { title: "Baasha", difficulty: "easy", popularity: "popular" },
  { title: "Padayappa", difficulty: "easy", popularity: "popular" },
  { title: "Annaatthe", difficulty: "easy", popularity: "popular" },
  { title: "Darbar", difficulty: "easy", popularity: "popular" },
  { title: "Petta", difficulty: "easy", popularity: "popular" },
  { title: "Bigil", difficulty: "easy", popularity: "popular" },
  { title: "Sarkar", difficulty: "easy", popularity: "popular" },
  { title: "Kaappaan", difficulty: "easy", popularity: "popular" },
  { title: "Comali", difficulty: "easy", popularity: "popular" },
  { title: "Kadaram Kondan", difficulty: "easy", popularity: "popular" },
  { title: "Jailer", difficulty: "easy", popularity: "popular" },
  { title: "Maamannan", difficulty: "easy", popularity: "popular" },
  { title: "Ponniyin Selvan 1", difficulty: "easy", popularity: "popular" },
  { title: "Ponniyin Selvan 2", difficulty: "easy", popularity: "popular" },
  { title: "Vettaiyan", difficulty: "easy", popularity: "popular" },
  { title: "Amaran", difficulty: "easy", popularity: "popular" },
  { title: "Indian 2", difficulty: "easy", popularity: "popular" },
  { title: "GOAT", difficulty: "easy", popularity: "popular" },
  { title: "Leo Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Lal Salaam", difficulty: "easy", popularity: "popular" },

  // ── EASY + NOT-SO-POPULAR ─────────────────────────────────────────────────
  { title: "Bommarillu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Nuvvostanante Nenoddantana", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Jalsa", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Pokiri Telugu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Athadu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Okkadu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Nannaku Prematho", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Iddari Lokam Okate", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Taxiwaala", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Nenu Sailaja", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Raja The Great", difficulty: "easy", popularity: "not-so-popular" },
  { title: "A Aa", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Pellichoopulu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Oh Baby", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Hushaaru", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Ishq Telugu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Ghilli", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Saamy", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Kaththi", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Puli Tamil", difficulty: "easy", popularity: "not-so-popular" },

  // ── EASY + RARELY-HEARD ───────────────────────────────────────────────────
  { title: "Anthapuram", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Prema Desam", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Chitram", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Subhalagnam", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Bavagaru Bagunnara", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Pelli Sandadi", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Shatamaanam Bhavati", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Tholi Prema 1998", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Hello Brother Telugu", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Muddula Mavayya", difficulty: "easy", popularity: "rarely-heard" },

  // ── MEDIUM + POPULAR (TELUGU) ─────────────────────────────────────────────
  { title: "Sye", difficulty: "medium", popularity: "popular" },
  { title: "Dubai Seenu", difficulty: "medium", popularity: "popular" },
  { title: "Mass Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Panjaa", difficulty: "medium", popularity: "popular" },
  { title: "Rebel Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Annavaram", difficulty: "medium", popularity: "popular" },
  { title: "Jersey Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Mahanati", difficulty: "medium", popularity: "popular" },
  { title: "C/O Kancharapalem", difficulty: "medium", popularity: "popular" },
  { title: "Agent Sai Srinivasa Athreya", difficulty: "medium", popularity: "popular" },
  { title: "Colour Photo", difficulty: "medium", popularity: "popular" },
  { title: "Love Story Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Uppena", difficulty: "medium", popularity: "popular" },
  { title: "Ante Sundaraniki", difficulty: "medium", popularity: "popular" },
  { title: "Karthikeya 2", difficulty: "medium", popularity: "popular" },
  { title: "Sita Ramam", difficulty: "medium", popularity: "popular" },
  { title: "Dasara Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Hi Nanna", difficulty: "medium", popularity: "popular" },
  { title: "Eagle Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Bhimaa", difficulty: "medium", popularity: "popular" },

  // ── MEDIUM + POPULAR (TAMIL) ──────────────────────────────────────────────
  { title: "Nayakan", difficulty: "medium", popularity: "popular" },
  { title: "Roja", difficulty: "medium", popularity: "popular" },
  { title: "Bombay Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Gentleman Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Iruvar", difficulty: "medium", popularity: "popular" },
  { title: "Kannathil Muthamittal", difficulty: "medium", popularity: "popular" },
  { title: "Alaipayuthey", difficulty: "medium", popularity: "popular" },
  { title: "Pithamagan", difficulty: "medium", popularity: "popular" },
  { title: "Ghajini Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Dasavathaaram", difficulty: "medium", popularity: "popular" },
  { title: "Vinnaithaandi Varuvaayaa", difficulty: "medium", popularity: "popular" },
  { title: "7aum Arivu", difficulty: "medium", popularity: "popular" },
  { title: "Nanban", difficulty: "medium", popularity: "popular" },
  { title: "Yennai Arindhaal", difficulty: "medium", popularity: "popular" },
  { title: "Vedalam", difficulty: "medium", popularity: "popular" },
  { title: "Theri", difficulty: "medium", popularity: "popular" },
  { title: "Kabali", difficulty: "medium", popularity: "popular" },
  { title: "Kaala", difficulty: "medium", popularity: "popular" },
  { title: "2.0 Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Sanga Tamizhan", difficulty: "medium", popularity: "popular" },

  // ── MEDIUM + NOT-SO-POPULAR ───────────────────────────────────────────────
  { title: "Anukokunda Oka Roju", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Ashta Chamma", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Avunu", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Awe!", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Middle Class Abbayi", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Drishyam Telugu", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Hit The First Case", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Hit 2", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Jathi Ratnalu", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Brochevarevaru Ra", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Thevar Magan", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Kadhal Tamil", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Mynaa", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Vaaranam Aayiram", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Kaadhal Kondein", difficulty: "medium", popularity: "not-so-popular" },

  // ── MEDIUM + RARELY-HEARD ─────────────────────────────────────────────────
  { title: "Mallesham", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Prathinidhi", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Mathu Vadalara", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Kshana Kshanam", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Swati Muthyam", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Iddaru Mitrulu", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Manmadha Telugu", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Autograph Tamil", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Mozhi", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Bommai", difficulty: "medium", popularity: "rarely-heard" },

  // ── HARD + POPULAR ────────────────────────────────────────────────────────
  { title: "Maro Charitra", difficulty: "hard", popularity: "popular" },
  { title: "Sankarabharanam", difficulty: "hard", popularity: "popular" },
  { title: "Sagara Sangamam", difficulty: "hard", popularity: "popular" },
  { title: "Mayabazar", difficulty: "hard", popularity: "popular" },
  { title: "Pathala Bhairavi", difficulty: "hard", popularity: "popular" },
  { title: "Missamma", difficulty: "hard", popularity: "popular" },
  { title: "Devadasu Telugu", difficulty: "hard", popularity: "popular" },
  { title: "Lava Kusa", difficulty: "hard", popularity: "popular" },
  { title: "Mullum Malarum", difficulty: "hard", popularity: "popular" },
  { title: "Apoorva Sagodharargal", difficulty: "hard", popularity: "popular" },

  // ── HARD + NOT-SO-POPULAR ─────────────────────────────────────────────────
  { title: "Subhalekha", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Meghadootam", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Palnati Yudham", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Alluri Seetarama Raju", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Maa Bhoomi", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Manchi Manasulu", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Raitu Bidda", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Ranga", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Naa Pellam Maa Abbayi", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Siva Telugu", difficulty: "hard", popularity: "not-so-popular" },

  // ── HARD + RARELY-HEARD ───────────────────────────────────────────────────
  { title: "Rangula Ratnam", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Telugu Veera Levara", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Rendu Rellu Aaru", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Gunde Jaari Gallanthayyinde", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Bhale Ramudu", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Idi Katha Kadu", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Sivaganga Seemai", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Nool Veli", difficulty: "hard", popularity: "rarely-heard" },

  // ── EASY + POPULAR Telugu (additional) ───────────────────────────────────
  { title: "Akhanda", difficulty: "easy", popularity: "popular" },
  { title: "Bimbisara", difficulty: "easy", popularity: "popular" },
  { title: "Bhimla Nayak", difficulty: "easy", popularity: "popular" },
  { title: "F2 Fun and Frustration", difficulty: "easy", popularity: "popular" },
  { title: "F3 Fun and Frustration", difficulty: "easy", popularity: "popular" },
  { title: "Krack", difficulty: "easy", popularity: "popular" },
  { title: "Most Eligible Bachelor", difficulty: "easy", popularity: "popular" },
  { title: "Bangarraju", difficulty: "easy", popularity: "popular" },
  { title: "Acharya", difficulty: "easy", popularity: "popular" },
  { title: "Radhe Shyam", difficulty: "easy", popularity: "popular" },
  { title: "Dhamaka Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Mangalavaaram", difficulty: "easy", popularity: "popular" },
  { title: "Bro Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Kushi Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Dil Raju Production Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Bhagavanth Kesari", difficulty: "easy", popularity: "popular" },
  { title: "Tiger Nageswara Rao", difficulty: "easy", popularity: "popular" },
  { title: "Salaar Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Lucky Baskhar Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Saripodhaa Sanivaaram", difficulty: "easy", popularity: "popular" },
  { title: "Devara Part 1", difficulty: "easy", popularity: "popular" },
  { title: "Pushpa 2 The Rule", difficulty: "easy", popularity: "popular" },
  { title: "Game Changer Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Daaku Maharaaj", difficulty: "easy", popularity: "popular" },
  { title: "Robinhood Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Ustaad Bhagat Singh", difficulty: "easy", popularity: "popular" },
  { title: "Double iSmart", difficulty: "easy", popularity: "popular" },
  { title: "Saaho Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Disco Raja", difficulty: "easy", popularity: "popular" },
  { title: "Ruler Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Balakrishna Latest", difficulty: "easy", popularity: "popular" },
  { title: "NTR Mahanayakudu", difficulty: "easy", popularity: "popular" },
  { title: "Kalki 2898 AD Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Sye Raa Narasimha Reddy Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Vinaya Vidheya Rama", difficulty: "easy", popularity: "popular" },
  { title: "Nannaku Prematho 2", difficulty: "easy", popularity: "popular" },
  { title: "Hello Telugu", difficulty: "easy", popularity: "popular" },
  { title: "Agnyaathavaasi", difficulty: "easy", popularity: "popular" },
  { title: "Trivikram Production", difficulty: "easy", popularity: "popular" },
  { title: "Bheemla Nayak", difficulty: "easy", popularity: "popular" },

  // ── EASY + POPULAR Tamil (additional) ────────────────────────────────────
  { title: "Mankatha", difficulty: "easy", popularity: "popular" },
  { title: "I Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Remo Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Bairavaa", difficulty: "easy", popularity: "popular" },
  { title: "Thaana Serndha Koottam", difficulty: "easy", popularity: "popular" },
  { title: "Jigarthanda DoubleX", difficulty: "easy", popularity: "popular" },
  { title: "Ayalaan", difficulty: "easy", popularity: "popular" },
  { title: "Maaveeran", difficulty: "easy", popularity: "popular" },
  { title: "Captain Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Bramayugam", difficulty: "easy", popularity: "popular" },
  { title: "Manjummel Boys", difficulty: "easy", popularity: "popular" },
  { title: "Aavesham", difficulty: "easy", popularity: "popular" },
  { title: "Premalu", difficulty: "easy", popularity: "popular" },
  { title: "Marco Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Thangalaan", difficulty: "easy", popularity: "popular" },
  { title: "Kanguva", difficulty: "easy", popularity: "popular" },
  { title: "Goat Life", difficulty: "easy", popularity: "popular" },
  { title: "Lubber Pandhu", difficulty: "easy", popularity: "popular" },
  { title: "Meiyazhagan", difficulty: "easy", popularity: "popular" },
  { title: "Amaran Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Soorarai Pottru 2", difficulty: "easy", popularity: "popular" },
  { title: "Raayan", difficulty: "easy", popularity: "popular" },
  { title: "Indian 3", difficulty: "easy", popularity: "popular" },
  { title: "GOAT Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Devara Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Maamannan Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Iraivan", difficulty: "easy", popularity: "popular" },
  { title: "Pathu Thala", difficulty: "easy", popularity: "popular" },
  { title: "Thunivu Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Viduthalai Part 1", difficulty: "easy", popularity: "popular" },
  { title: "Viduthalai Part 2", difficulty: "easy", popularity: "popular" },
  { title: "Durai Singam", difficulty: "easy", popularity: "popular" },
  { title: "Singam", difficulty: "easy", popularity: "popular" },
  { title: "Singam 2", difficulty: "easy", popularity: "popular" },
  { title: "Singam 3", difficulty: "easy", popularity: "popular" },
  { title: "Theri Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Mersal Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Sarkar Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Bigil Tamil", difficulty: "easy", popularity: "popular" },
  { title: "Beast Tamil", difficulty: "easy", popularity: "popular" },

  // ── EASY + NOT-SO-POPULAR (additional) ───────────────────────────────────
  { title: "Prabhas Mirchi", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Rebel Telugu 2", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Julayi Telugu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Dookudu Telugu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Sukumar Film", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Geetha Govindam 2", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Bheeshma Telugu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Sarrainodu Telugu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Nenu Sailaja Telugu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Gopala Gopala", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Pataas", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Power Telugu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Loukyam", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Aagadu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Masala Telugu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Rebel Tamil", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Ko Tamil", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Ko 2 Tamil", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Thupparivaalan", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Thupparivaalan 2", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Kee Tamil", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Kannaana Kanney", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Seethakathi", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Nenjam Marappathillai", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Sandakozhi", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Sandakozhi 2", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Saamy Tamil", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Naan Sigappu Manithan", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Vai Raja Vai", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Thamizh Padam", difficulty: "easy", popularity: "not-so-popular" },

  // ── EASY + RARELY-HEARD (additional) ─────────────────────────────────────
  { title: "Missiamma Telugu", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Pelli Chesi Choodu", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Maya Bazaar Tamil", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Veerapandiya Kattabomman", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Nadodi Mannan", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Thirudathe", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Anbe Vaa", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Nenjil Oru Aalayam", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Enga Veettu Pillai", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Aval Appadithan", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Apoorva Raagangal", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Ninaithale Inikkum", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Moondram Pirai", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Nayagan Roja", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Pathinaaru Vayathinile", difficulty: "easy", popularity: "rarely-heard" },

  // ── MEDIUM + POPULAR Telugu (additional) ─────────────────────────────────
  { title: "1 Nenokkadine", difficulty: "medium", popularity: "popular" },
  { title: "Attarintiki Daredi", difficulty: "medium", popularity: "popular" },
  { title: "Legend Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Kaththi Sandai", difficulty: "medium", popularity: "popular" },
  { title: "Rangasthalam", difficulty: "medium", popularity: "popular" },
  { title: "Mahanati Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Goodachari", difficulty: "medium", popularity: "popular" },
  { title: "Evaru", difficulty: "medium", popularity: "popular" },
  { title: "V Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Maestro Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Republic Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Vakeel Saab", difficulty: "medium", popularity: "popular" },
  { title: "Major Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Virata Parvam", difficulty: "medium", popularity: "popular" },
  { title: "Bheeshma Parvam", difficulty: "medium", popularity: "popular" },
  { title: "Romancham", difficulty: "medium", popularity: "popular" },
  { title: "Hanu-Man", difficulty: "medium", popularity: "popular" },
  { title: "Prema Vivaham", difficulty: "medium", popularity: "popular" },
  { title: "Orey Bujjiga", difficulty: "medium", popularity: "popular" },
  { title: "Nani Dasara", difficulty: "medium", popularity: "popular" },
  { title: "Dasara Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Shyam Singha Roy", difficulty: "medium", popularity: "popular" },
  { title: "Check Telugu", difficulty: "medium", popularity: "popular" },
  { title: "Tuck Jagadish", difficulty: "medium", popularity: "popular" },
  { title: "Nenu Naa Boyfriends", difficulty: "medium", popularity: "popular" },
  { title: "Pelli SandaD", difficulty: "medium", popularity: "popular" },
  { title: "Ambajipeta Marriage Band", difficulty: "medium", popularity: "popular" },
  { title: "Balagam", difficulty: "medium", popularity: "popular" },
  { title: "Seethamma Vakitlo", difficulty: "medium", popularity: "popular" },
  { title: "Dil Dhadakne Do Telugu", difficulty: "medium", popularity: "popular" },

  // ── MEDIUM + POPULAR Tamil (additional) ──────────────────────────────────
  { title: "Naanum Rowdy Dhaan", difficulty: "medium", popularity: "popular" },
  { title: "Vikram Vedha Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Theeran Adhigaaram Ondru", difficulty: "medium", popularity: "popular" },
  { title: "Adanga Maru", difficulty: "medium", popularity: "popular" },
  { title: "Iruttu Araiyil Murattu Kuththu", difficulty: "medium", popularity: "popular" },
  { title: "Meaghamann", difficulty: "medium", popularity: "popular" },
  { title: "Inaindha Kaigal", difficulty: "medium", popularity: "popular" },
  { title: "Viswaroopam", difficulty: "medium", popularity: "popular" },
  { title: "Thalaivar", difficulty: "medium", popularity: "popular" },
  { title: "Chandramukhi", difficulty: "medium", popularity: "popular" },
  { title: "Chandramukhi 2", difficulty: "medium", popularity: "popular" },
  { title: "Kochadaiiyaan", difficulty: "medium", popularity: "popular" },
  { title: "Lingaa", difficulty: "medium", popularity: "popular" },
  { title: "Kabali Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Kaala Tamil", difficulty: "medium", popularity: "popular" },
  { title: "2.0 Tamil 2", difficulty: "medium", popularity: "popular" },
  { title: "Darbar Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Annaatthe Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Coolie Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Thunivu Tamil 2", difficulty: "medium", popularity: "popular" },
  { title: "Thalapathi Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Muthu Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Basha Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Padayappa Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Sivaji The Boss", difficulty: "medium", popularity: "popular" },
  { title: "Enthiran Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Ra One Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Nanban Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Kochadaiyaan Tamil", difficulty: "medium", popularity: "popular" },
  { title: "Kaaviya Thalaivan", difficulty: "medium", popularity: "popular" },

  // ── MEDIUM + NOT-SO-POPULAR (additional) ─────────────────────────────────
  { title: "Nuvvu Nenu", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Gattimela", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Ishq Telugu 2", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Oohalu Gusagusalade", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Nenu Sailaja Remake", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Shatamanam Bhavati Telugu", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Chitralahari", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Nirmala Convent", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Sailaja Reddy Alludu", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Rabhasa", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Aagadu Telugu 2", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Ko Tamil Classic", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Naan Mahaan Alla", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Varuthapadatha Valibar Sangam", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Kaaki Sattai", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Nannbenda", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Manithan", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Remo Tamil 2", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Meyaadha Maan", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Saahasam Swaasaga Saagipo", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Adavi Ramudu", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Kondapalli Raja", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Hitler Telugu", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Bobbili Raja", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Mutha Mestri", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Annayya", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Idiot Telugu", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Julai Telugu", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Cameraman Ganga Tho Rambabu", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Yevadu", difficulty: "medium", popularity: "not-so-popular" },

  // ── MEDIUM + RARELY-HEARD (additional) ───────────────────────────────────
  { title: "Ee. Ma. Yau", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Jallikattu", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Kumbalangi Nights", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Angamaly Diaries", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Virus Malayalam", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Drishyam Malayalam", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Trance Malayalam", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Thondimuthalum Driksakshiyum", difficulty: "medium", popularity: "rarely-heard" },
  { title: "C U Soon", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Minnal Murali", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Jana Gana Mana Malayalam", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Hridayam", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Churuli", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Malik", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Kurup", difficulty: "medium", popularity: "rarely-heard" },

  // ── HARD + POPULAR (additional) ───────────────────────────────────────────
  { title: "Deiva Magan Tamil", difficulty: "hard", popularity: "popular" },
  { title: "Parasakthi", difficulty: "hard", popularity: "popular" },
  { title: "Thiruvilaiyadal", difficulty: "hard", popularity: "popular" },
  { title: "Enga Veettu Pillai Classic", difficulty: "hard", popularity: "popular" },
  { title: "Thillana Mohanambal", difficulty: "hard", popularity: "popular" },
  { title: "Shankar Dada", difficulty: "hard", popularity: "popular" },
  { title: "Naam Iruvar Namakku Iruvar", difficulty: "hard", popularity: "popular" },
  { title: "Kappalottiya Thamizhan", difficulty: "hard", popularity: "popular" },
  { title: "Gnana Oli", difficulty: "hard", popularity: "popular" },
  { title: "Sorgam Tamil", difficulty: "hard", popularity: "popular" },
  { title: "Maalai Pozhudhin Mayakathiley", difficulty: "hard", popularity: "popular" },
  { title: "Bhadrakali Telugu", difficulty: "hard", popularity: "popular" },
  { title: "Bhale Bhale Mogadivoy", difficulty: "hard", popularity: "popular" },
  { title: "Pattabhi Ramayya Telugu", difficulty: "hard", popularity: "popular" },
  { title: "Dasara Bullodu", difficulty: "hard", popularity: "popular" },
  { title: "Jagadeka Veerudu Atiloka Sundari", difficulty: "hard", popularity: "popular" },
  { title: "Mutha Mestri Classic", difficulty: "hard", popularity: "popular" },
  { title: "Stuartpuram Police Station", difficulty: "hard", popularity: "popular" },
  { title: "Rowdy Alludu", difficulty: "hard", popularity: "popular" },
  { title: "Yamudiki Mogudu", difficulty: "hard", popularity: "popular" },

  // ── HARD + NOT-SO-POPULAR (additional) ────────────────────────────────────
  { title: "Piravi Malayalam", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Elippathayam Malayalam", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Chemmeen", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Nirmalyam", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Kodiyettam Malayalam", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Swapnadanam", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Uttarayanam", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Aval Appadithan Tamil", difficulty: "hard", popularity: "not-so-popular" },
  { title: "16 Vayathinile", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Apoorva Raagangal Tamil", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Ninaithale Inikkum Tamil", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Nool Veli Tamil", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Nizhalgal Tamil", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Moondram Pirai Tamil", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Murattu Kaalai", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Nambiyaar", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Oru Naal Iravil", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Njan Gandharvan", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Thazhvaram", difficulty: "hard", popularity: "not-so-popular" },
  { title: "Sandesham Malayalam", difficulty: "hard", popularity: "not-so-popular" },

  // ── HARD + RARELY-HEARD (additional) ──────────────────────────────────────
  { title: "Manichitrathazhu", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Bharatham Malayalam", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Aalkkoottathil Thaniye", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Poovannam", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Deshanadhan", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Pathram Malayalam", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Kazhukan", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Perumazhakkalam", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Aayiram Palakal", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Thuruppugulan", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Nandanam Malayalam", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Chattambinadu", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Chathurangam Malayalam", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Kavyam Kannada", difficulty: "hard", popularity: "rarely-heard" },
  { title: "Duniya Kannada", difficulty: "hard", popularity: "rarely-heard" },

  // ── EASY + POPULAR (final additions) ─────────────────────────────────────
  { title: "Vikrant Rona", difficulty: "easy", popularity: "popular" },
  { title: "KGF Chapter 1 Kannada", difficulty: "easy", popularity: "popular" },
  { title: "KGF Chapter 2 Kannada", difficulty: "easy", popularity: "popular" },
  { title: "777 Charlie", difficulty: "easy", popularity: "popular" },
  { title: "Kantara", difficulty: "easy", popularity: "popular" },
  { title: "Ugramm", difficulty: "easy", popularity: "popular" },
  { title: "Mungaru Male", difficulty: "easy", popularity: "popular" },
  { title: "Raajakumara Kannada", difficulty: "easy", popularity: "popular" },
  { title: "Kirik Party", difficulty: "easy", popularity: "popular" },
  { title: "Bell Bottom Kannada", difficulty: "easy", popularity: "popular" },
  { title: "Tagaru Kannada", difficulty: "easy", popularity: "popular" },
  { title: "Kavaludaari Kannada", difficulty: "easy", popularity: "popular" },
  { title: "Dia Kannada", difficulty: "easy", popularity: "popular" },
  { title: "Love Mocktail", difficulty: "easy", popularity: "popular" },
  { title: "Garuda Gamana Vrishabha Vahana", difficulty: "easy", popularity: "popular" },
  { title: "Banaras Kannada", difficulty: "easy", popularity: "popular" },
  { title: "Bagheera Kannada", difficulty: "easy", popularity: "popular" },
  { title: "UI Kannada", difficulty: "easy", popularity: "popular" },
  { title: "Kabzaa Kannada", difficulty: "easy", popularity: "popular" },
  { title: "Salaga Kannada", difficulty: "easy", popularity: "popular" },
  { title: "Yuvarathnaa Kannada", difficulty: "easy", popularity: "popular" },
  { title: "Roberrt Kannada", difficulty: "easy", popularity: "popular" },
];
