const MOVIES_TOLLYWOOD = [
  { title: "RRR", difficulty: "easy", popularity: "popular" },
  { title: "Baahubali", difficulty: "easy", popularity: "popular" },
  { title: "Baahubali 2", difficulty: "easy", popularity: "popular" },
  { title: "Pushpa", difficulty: "easy", popularity: "popular" },
  { title: "Arjun Reddy", difficulty: "easy", popularity: "popular" },
  { title: "Magadheera", difficulty: "easy", popularity: "popular" },
  { title: "Eega", difficulty: "easy", popularity: "popular" },
  { title: "Vikram", difficulty: "easy", popularity: "popular" },
  { title: "Jailer", difficulty: "easy", popularity: "popular" },
  { title: "Master", difficulty: "easy", popularity: "popular" },
  { title: "KGF Chapter 2", difficulty: "easy", popularity: "popular" },
  { title: "Kantara", difficulty: "easy", popularity: "popular" },
  { title: "Jai Bhim", difficulty: "easy", popularity: "popular" },
  { title: "96", difficulty: "easy", popularity: "popular" },
  { title: "Okkadu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Pokiri", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Bommarillu", difficulty: "easy", popularity: "not-so-popular" },
  { title: "Sita Ramam", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Mahanati", difficulty: "easy", popularity: "rarely-heard" },
  { title: "Roja", difficulty: "medium", popularity: "popular" },
  { title: "Nayakan", difficulty: "medium", popularity: "popular" },
  { title: "Vikram Vedha", difficulty: "medium", popularity: "popular" },
  { title: "Mersal", difficulty: "medium", popularity: "popular" },
  { title: "Enthiran", difficulty: "medium", popularity: "popular" },
  { title: "Kaithi", difficulty: "medium", popularity: "popular" },
  { title: "Soorarai Pottru", difficulty: "medium", popularity: "popular" },
  { title: "Drishyam", difficulty: "medium", popularity: "popular" },
  { title: "Ghilli", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Saamy", difficulty: "medium", popularity: "not-so-popular" },
  { title: "Kshana Kshanam", difficulty: "medium", popularity: "rarely-heard" },
  { title: "Thevar Magan", difficulty: "hard", popularity: "popular" },
  { title: "Mullum Malarum", difficulty: "hard", popularity: "popular" },
  { title: "Aval Appadithan", difficulty: "hard", popularity: "not-so-popular" },
];
